# Generated by Django 5.2.5 on 2026-03-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_settings', '0006_desktoprelease_android_apk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_customer_assignments', to='core_settings.companysettings')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
                'indexes': [models.Index(fields=['company', 'customer', 'unassigned_at'], name='hierarchy_a_company_2b8977_idx'), models.Index(fields=['company', 'agent', 'unassigned_at'], name='hierarchy_a_company_e61a63_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('company', 'customer'), name='uniq_active_assignment_per_customer_company')],
            },
        ),
    ]
