# Generated by Django 5.2.5 on 2026-03-10 12:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0023_hybrid_sync_models'),
        ('khataapp', '0009_companysettings_auto_sms_send'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], db_index=True, max_length=20)),
                ('username', models.CharField(db_index=True, max_length=80, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('api_token', models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True)),
                ('api_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('api_token_last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_accounts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accounts', to=settings.AUTH_USER_MODEL)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_account', to='khataapp.party')),
            ],
            options={
                'db_table': 'portal_users',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('allowed', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='portal.portaluser')),
            ],
            options={
                'db_table': 'portal_permissions',
            },
        ),
        migrations.CreateModel(
            name='PortalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commerce_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_mappings', to='commerce.order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_orders_owner', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_orders', to='khataapp.party')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_orders', to='portal.portaluser')),
            ],
            options={
                'db_table': 'portal_orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('provider', models.CharField(blank=True, default='upi', max_length=40)),
                ('status', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='created', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='commerce.invoice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to=settings.AUTH_USER_MODEL)),
                ('portal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='portal.portaluser')),
            ],
            options={
                'db_table': 'payment_links',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_cart_items', to='commerce.product')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='portal.portaluser')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20)),
                ('to', models.CharField(blank=True, default='', max_length=180)),
                ('message_preview', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_message_logs', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_message_logs', to='khataapp.party')),
                ('portal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_message_logs', to='portal.portaluser')),
            ],
            options={
                'db_table': 'welcome_messages_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='portaluser',
            index=models.Index(fields=['owner', 'role', 'is_active'], name='portal_owner_role_act_idx'),
        ),
        migrations.AddIndex(
            model_name='portaluser',
            index=models.Index(fields=['owner', 'created_at'], name='portal_owner_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='portalpermission',
            index=models.Index(fields=['portal_user', 'allowed'], name='portal_perm_user_allow_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalpermission',
            constraint=models.UniqueConstraint(fields=('portal_user', 'key'), name='uniq_portal_perm_user_key'),
        ),
        migrations.AddIndex(
            model_name='portalorder',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='portal_order_owner_st_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='portalorder',
            index=models.Index(fields=['portal_user', 'created_at'], name='portal_order_user_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='paylink_owner_st_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['invoice', 'status'], name='paylink_inv_st_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['portal_user', 'updated_at'], name='portal_cart_user_upd_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('portal_user', 'product'), name='uniq_portal_cart_user_product'),
        ),
        migrations.AddIndex(
            model_name='welcomemessagelog',
            index=models.Index(fields=['owner', 'created_at'], name='wel_msg_owner_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='welcomemessagelog',
            index=models.Index(fields=['owner', 'channel', 'status'], name='wel_msg_owner_ch_st_idx'),
        ),
    ]
