# Generated by Django 5.2.5 on 2026-03-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_settings', '0006_desktoprelease_android_apk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('iso2', models.CharField(blank=True, db_index=True, max_length=2)),
                ('iso3', models.CharField(blank=True, max_length=3)),
                ('phone_code', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Optional tenant scope. Keep null for global master data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='core_settings.companysettings')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Optional tenant scope. Keep null for global master data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core_settings.companysettings')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('locality', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=160)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Optional tenant scope. Keep null for global master data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes', to='core_settings.companysettings')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pincodes', to='location.district')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Optional tenant scope. Keep null for global master data.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core_settings.companysettings')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='location.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='location.state'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['company', 'name'], name='location_co_company_24f803_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['company', 'iso2'], name='location_co_company_f0b5ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_country_company_name'),
        ),
        migrations.AddIndex(
            model_name='pincode',
            index=models.Index(fields=['company', 'code'], name='location_pi_company_327631_idx'),
        ),
        migrations.AddIndex(
            model_name='pincode',
            index=models.Index(fields=['district', 'code'], name='location_pi_distric_1c0ca9_idx'),
        ),
        migrations.AddConstraint(
            model_name='pincode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_pincode_company_code'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['company', 'country', 'name'], name='location_st_company_84bdf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('company', 'country', 'name'), name='uniq_state_company_country_name'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['company', 'state', 'name'], name='location_di_company_e2a94d_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('company', 'state', 'name'), name='uniq_district_company_state_name'),
        ),
    ]
