# Generated by Django 5.2.5 on 2026-03-19 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_settings', '0006_desktoprelease_android_apk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(db_index=True, default='note', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('mobile', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('website', 'Website'), ('referral', 'Referral'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost'), ('inactive', 'Inactive')], db_index=True, default='new', max_length=20)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('pincode_text', models.CharField(blank=True, default='', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('next_followup_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core_settings.companysettings')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
