# Generated by Django 5.2.5 on 2026-05-10 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'reporting_categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('result_preview', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('print', 'Print')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='report_exports/')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='platform_reporting.reportrun')),
            ],
            options={
                'db_table': 'reporting_exports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('report_type', models.CharField(choices=[('table', 'Table'), ('kpi', 'KPI'), ('chart', 'Chart'), ('pivot', 'Pivot'), ('statement', 'Statement')], db_index=True, default='table', max_length=30)),
                ('domain', models.CharField(db_index=True, max_length=80)),
                ('source_model', models.CharField(blank=True, default='', max_length=160)),
                ('query_spec', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('chart_spec', models.JSONField(blank=True, default=dict)),
                ('permission_key', models.CharField(blank=True, default='', max_length=180)),
                ('cache_seconds', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='platform_reporting.reportcategory')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'reporting_templates',
                'ordering': ('domain', 'name'),
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.AddField(
            model_name='reportrun',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='platform_reporting.reporttemplate'),
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('domain', models.CharField(db_index=True, max_length=80)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('period', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('dimension', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'reporting_analytics_metrics',
                'ordering': ('domain', 'key'),
                'unique_together': {('tenant', 'key', 'period')},
            },
        ),
        migrations.CreateModel(
            name='RealtimeDashboardCounter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('channel', models.CharField(db_index=True, default='reports', max_length=120)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'reporting_realtime_counters',
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SavedReportFilter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=160)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='platform_reporting.reporttemplate')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_saved_filters',
                'unique_together': {('template', 'user', 'name')},
            },
        ),
    ]
