# Generated by Django 5.2.5 on 2026-03-10 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='bank_statements/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('previewed', 'Previewed'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_import_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='bankimp_owner_dt_idx'), models.Index(fields=['owner', 'status', 'created_at'], name='bankimp_owner_st_dt_idx')],
            },
        ),
    ]
