# Generated by Django 5.2.5 on 2026-05-18 08:53

import distribution.models
import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('platform_type', models.CharField(choices=[('web', 'Web App'), ('android_apk', 'Android APK'), ('desktop_exe', 'Desktop EXE'), ('embedded_pos', 'Embedded POS'), ('self_checkout', 'Self Checkout Kiosk'), ('pwa', 'PWA'), ('tablet_pos', 'Tablet POS'), ('mobile_pos', 'Mobile POS'), ('windows', 'Windows Installer'), ('linux', 'Linux Installer'), ('mac', 'Mac Installer')], db_index=True, max_length=30)),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='store', max_length=80)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_uid', models.CharField(max_length=140, unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('desktop', 'Desktop'), ('pos', 'POS'), ('kiosk', 'Kiosk'), ('embedded', 'Embedded'), ('pwa', 'PWA')], db_index=True, max_length=30)),
                ('app_version', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('last_config_version', models.PositiveIntegerField(default=0)),
                ('authorized', models.BooleanField(db_index=True, default=True)),
                ('license_key_hash', models.CharField(blank=True, default='', max_length=128)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_devices', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='distribution.appplatform')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='distribution.industry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='sparkles', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(db_index=True, default='1.0.0', max_length=40)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('rollout_status', models.CharField(choices=[('draft', 'Draft'), ('beta', 'Beta'), ('rollout', 'Rollout'), ('stable', 'Stable'), ('disabled', 'Disabled')], db_index=True, default='stable', max_length=20)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('remote_payload', models.JSONField(blank=True, default=dict)),
                ('supported_platforms', models.ManyToManyField(blank=True, related_name='features', to='distribution.appplatform')),
                ('industries', models.ManyToManyField(blank=True, related_name='features', to='distribution.industry')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('module_type', models.CharField(choices=[('page', 'Page'), ('menu', 'Menu'), ('dashboard_card', 'Dashboard Card'), ('report', 'Report'), ('pos_module', 'POS Module'), ('kiosk_module', 'Kiosk Module'), ('plugin', 'Plugin')], db_index=True, default='page', max_length=30)),
                ('icon', models.CharField(blank=True, default='grid', max_length=80)),
                ('route_path', models.CharField(blank=True, default='', max_length=240)),
                ('api_endpoint', models.CharField(blank=True, default='', max_length=240)),
                ('component_key', models.CharField(blank=True, default='', max_length=120)),
                ('version', models.CharField(db_index=True, default='1.0.0', max_length=40)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('lazy_load', models.BooleanField(default=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('remote_payload', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('features', models.ManyToManyField(blank=True, related_name='modules', to='distribution.featureregistry')),
                ('industries', models.ManyToManyField(blank=True, related_name='modules', to='distribution.industry')),
                ('supported_platforms', models.ManyToManyField(blank=True, related_name='modules', to='distribution.appplatform')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('build_type', models.CharField(choices=[('apk', 'Android APK'), ('desktop', 'Desktop'), ('pos', 'POS Installer'), ('kiosk', 'Self Checkout'), ('embedded', 'Embedded POS'), ('web', 'Web URL'), ('pwa', 'PWA'), ('play_store', 'Google Play'), ('app_store', 'App Store'), ('india_store', 'Indian App Store'), ('windows', 'Windows'), ('linux', 'Linux'), ('mac', 'Mac')], db_index=True, max_length=30)),
                ('version', models.CharField(db_index=True, default='1.0.0', max_length=50)),
                ('build_number', models.CharField(blank=True, default='', max_length=60)),
                ('installer_file', models.FileField(blank=True, null=True, upload_to='distribution/builds/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('play_store_url', models.URLField(blank=True, default='')),
                ('app_store_url', models.URLField(blank=True, default='')),
                ('pwa_url', models.URLField(blank=True, default='')),
                ('web_launch_url', models.URLField(blank=True, default='')),
                ('release_notes', models.TextField(blank=True, default='')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('signature', models.CharField(blank=True, default='', max_length=160)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('allow_public_download', models.BooleanField(db_index=True, default=True)),
                ('requires_login', models.BooleanField(db_index=True, default=False)),
                ('min_license_tier', models.CharField(blank=True, default='', max_length=60)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='software_builds', to='distribution.industry')),
                ('modules', models.ManyToManyField(blank=True, related_name='software_builds', to='distribution.moduleregistry')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_builds', to='distribution.appplatform')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=80, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=distribution.models.default_download_token_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_tokens', to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='distribution.softwarebuild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=True)),
                ('can_launch', models.BooleanField(default=True)),
                ('can_install_beta', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_permissions', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_permissions', to='distribution.industry')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_permissions', to='distribution.softwarebuild')),
            ],
        ),
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installed_version', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(db_index=True, default='installed', max_length=30)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='distribution.deviceregistry')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='distribution.softwarebuild')),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(db_index=True, max_length=50)),
                ('min_supported_version', models.CharField(blank=True, default='', max_length=50)),
                ('force_update', models.BooleanField(db_index=True, default=False)),
                ('update_message', models.CharField(blank=True, default='', max_length=240)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='distribution.appplatform')),
            ],
            options={
                'unique_together': {('platform', 'version')},
            },
        ),
        migrations.CreateModel(
            name='IndustryModuleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(db_index=True, default=True)),
                ('default_enabled', models.BooleanField(db_index=True, default=True)),
                ('config_overrides', models.JSONField(blank=True, default=dict)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_maps', to='distribution.industry')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_maps', to='distribution.moduleregistry')),
            ],
            options={
                'unique_together': {('industry', 'module')},
            },
        ),
        migrations.CreateModel(
            name='RemoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('industry', 'Industry'), ('user', 'User'), ('device', 'Device')], db_index=True, default='global', max_length=20)),
                ('device_uid', models.CharField(blank=True, db_index=True, default='', max_length=140)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(db_index=True, default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_configs', to='distribution.industry')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('key', 'scope', 'industry', 'user', 'device_uid')},
            },
        ),
        migrations.AddIndex(
            model_name='softwarebuild',
            index=models.Index(fields=['build_type', 'is_published'], name='distributio_build_t_9b1016_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarebuild',
            index=models.Index(fields=['slug', 'version'], name='distributio_slug_62069d_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadpermission',
            index=models.Index(fields=['user', 'build'], name='distributio_user_id_46fb4d_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadpermission',
            index=models.Index(fields=['industry', 'build'], name='distributio_industr_c4aea5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appinstallation',
            unique_together={('device', 'build')},
        ),
    ]
