# Generated by Django 5.2.5 on 2026-05-24 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=140, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('scope', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('mobile', 'Mobile'), ('company', 'Company')], db_index=True, default='private', max_length=20)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('secret', 'Secret')], default='string', max_length=20)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('encrypted_value', models.TextField(blank=True, default='')),
                ('env_key', models.CharField(blank=True, default='', max_length=120)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('help_text', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scope', 'key'),
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=160)),
                ('operation_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='received', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sync_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=180)),
                ('model_key', models.CharField(db_index=True, max_length=180)),
                ('operation', models.CharField(db_index=True, max_length=30)),
                ('object_pk', models.CharField(blank=True, default='', max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=30)),
                ('error', models.TextField(blank=True, default='')),
                ('client_timestamp', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.offlinesyncbatch')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(db_index=True, max_length=180)),
                ('object_pk', models.CharField(db_index=True, max_length=180)),
                ('server_snapshot', models.JSONField(blank=True, default=dict)),
                ('client_payload', models.JSONField(blank=True, default=dict)),
                ('policy', models.CharField(default='server_timestamp_wins', max_length=80)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='core.offlinesyncoperation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='offlinesyncoperation',
            index=models.Index(fields=['model_key', 'operation', 'status'], name='core_offlin_model_k_d42296_idx'),
        ),
    ]
