# Generated by Django 5.2.5 on 2026-03-19 12:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('signup', 'Signup'), ('subscription', 'Subscription'), ('renewal', 'Renewal'), ('bonus', 'Bonus'), ('order', 'Order')], db_index=True, max_length=20)),
                ('role', models.CharField(choices=[('super_admin', 'SuperAdmin'), ('state_admin', 'StateAdmin'), ('district_admin', 'DistrictAdmin'), ('area_admin', 'AreaAdmin'), ('super_agent', 'SuperAgent'), ('agent', 'Agent'), ('customer', 'Customer')], db_index=True, max_length=20)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_type', 'role'],
                'unique_together': {('event_type', 'role')},
            },
        ),
    ]
