# Generated by Django 5.2.5 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_commissionscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionscheme',
            name='event_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('subscription', 'Subscription'), ('renewal', 'Renewal'), ('bonus', 'Bonus'), ('order', 'Order'), ('call_conversion', 'Call Conversion'), ('qr_scan', 'QR Scan'), ('shop_onboarding', 'Shop Onboarding'), ('voice_close', 'Voice AI Close')], db_index=True, max_length=20),
        ),
    ]
