# Generated by Django 5.2.5 on 2026-06-03 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaistech_erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='error', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=20)),
                ('source', models.CharField(db_index=True, default='backend', max_length=80)),
                ('endpoint', models.CharField(blank=True, db_index=True, default='', max_length=240)),
                ('method', models.CharField(blank=True, default='', max_length=12)),
                ('status_code', models.PositiveIntegerField(default=500)),
                ('problem', models.TextField()),
                ('root_cause', models.TextField(blank=True, default='')),
                ('recommended_fix', models.TextField(blank=True, default='')),
                ('exception', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='jaistech_er_status_5673ac_idx'), models.Index(fields=['endpoint', 'status'], name='jaistech_er_endpoin_d0c3e5_idx')],
            },
        ),
    ]
