# Generated by Django 5.2.5 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('voice_success', 'Voice call success %'), ('qr_to_signup', 'QR scan to signup ratio'), ('wa_conversion', 'WhatsApp conversion rate'), ('agent_heatmap', 'Agent performance heatmap')], db_index=True, max_length=40)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['metric', 'period_start', 'period_end'], name='eng_metric_idx')],
            },
        ),
    ]
