# Generated by Django 5.2.5 on 2026-03-10 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('duplicate_invoice', 'Duplicate Invoice'), ('gst_mismatch', 'GST Mismatch'), ('negative_stock', 'Negative Stock'), ('suspicious_txn', 'Suspicious Transaction')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=10)),
                ('reference_type', models.CharField(db_index=True, max_length=100)),
                ('reference_id', models.PositiveBigIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_fraud_alerts',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'status', 'created_at'], name='val_fraud_owner_st_dt_idx'), models.Index(fields=['owner', 'alert_type', 'created_at'], name='val_fraud_owner_tp_dt_idx'), models.Index(fields=['reference_type', 'reference_id'], name='val_fraud_ref_idx')],
            },
        ),
    ]
