# Generated by Codex on 2026-04-07

from __future__ import annotations

from django.db import migrations


def ensure_validation_fraud_alerts_table(apps, schema_editor):
    """
    Some existing SQLite databases were created when `validation.FraudAlert`
    used `db_table="fraud_alerts"`. The code now expects
    `db_table="validation_fraud_alerts"`.

    If the expected table is missing, create it without touching any existing
    `fraud_alerts` table (which may belong to another app).
    """

    existing_tables = set(schema_editor.connection.introspection.table_names())
    if "validation_fraud_alerts" in existing_tables:
        return

    FraudAlert = apps.get_model("validation", "FraudAlert")
    schema_editor.create_model(FraudAlert)


class Migration(migrations.Migration):
    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(ensure_validation_fraud_alerts_table, reverse_code=migrations.RunPython.noop),
    ]

