# Generated by Django 5.2.5 on 2026-02-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_remove_journalvoucherline_journal_line_non_negative_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("invoice", "Invoice"), ("order", "Order"), ("voucher", "Voucher"), ("payment", "Payment"), ("cash_paid", "Cash Paid"), ("online_paid", "Online Paid"), ("pdc", "PDC"), ("advance", "Advance"), ("regular", "Regular"), ("gst", "GST"), ("non_gst", "Non-GST"), ("not_applicable", "Not Applicable")], db_index=True, default="not_applicable", max_length=30)),
                ("reference_type", models.CharField(db_index=True, max_length=100)),
                ("reference_id", models.PositiveBigIntegerField(db_index=True)),
                ("voucher_type", models.CharField(blank=True, db_index=True, default="", max_length=30)),
                ("receipt_no", models.CharField(blank=True, default="", max_length=64)),
                ("gst_enabled", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gl_transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="receipts", to="ledger.ledgertransaction")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="receipts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "kind", "created_at"], name="idx_receipt_owner_kind_dt"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(fields=("owner", "reference_type", "reference_id", "voucher_type"), name="uniq_receipt_owner_source"),
        ),
    ]

