# Generated by Django 5.2.5 on 2026-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_return_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='voucher_type',
            field=models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('expense', 'Expense'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('journal', 'Journal')], db_index=True, max_length=30),
        ),
    ]
