# Generated by Django 5.2.5 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0006_desktoprelease_android_apk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresettings',
            name='feature',
            field=models.CharField(choices=[('otp', 'OTP System'), ('emi', 'EMI'), ('gst', 'GST'), ('chat', 'Chat'), ('payment_gateway', 'Payment Gateway'), ('notification', 'Notifications'), ('daily_summary', 'Daily Summary'), ('voice_ai', 'Voice AI Calling'), ('qr_system', 'QR Onboarding'), ('whatsapp_mini', 'WhatsApp Mini App'), ('shop_onboarding', 'Shop Onboarding')], max_length=50, unique=True),
        ),
    ]
