# Generated by Django 5.2.5 on 2026-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0008_landingvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landing/clients/')),
                ('website_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Landing Client',
                'verbose_name_plural': 'Landing Clients',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LandingMarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('icon', models.CharField(blank=True, default='', help_text='Optional icon name (Bootstrap/FontAwesome).', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Landing Feature',
                'verbose_name_plural': 'Landing Features',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Billentra', max_length=120)),
                ('hero_kicker', models.CharField(blank=True, default='Smart Billing • Easy Business', max_length=140)),
                ('hero_title', models.CharField(default='Billing & Khata software built for Indian small businesses', max_length=220)),
                ('hero_subtitle', models.TextField(blank=True, default='Create GST invoices, manage inventory, track ledger/khata, and get reports in one clean, fast system.')),
                ('stat_businesses', models.PositiveIntegerField(default=45000)),
                ('stat_invoices', models.PositiveIntegerField(default=1250000)),
                ('stat_reports', models.PositiveIntegerField(default=98000)),
                ('clients_title', models.CharField(blank=True, default='They “Work With Us” — As Clients and Collaborators', max_length=220)),
                ('usecases_kicker', models.CharField(blank=True, default='Designed for Every Business, Big or Small', max_length=200)),
                ('usecases_title', models.CharField(blank=True, default='Who can use Billentra?', max_length=200)),
                ('usecases_subtitle', models.TextField(blank=True, default='Whether you run a retail store, wholesale business, or service-based company — Billentra helps you manage billing, inventory, khata and reports with a clean workflow.')),
                ('videos_kicker', models.CharField(blank=True, default='A Peek Into Billentra', max_length=140)),
                ('videos_title', models.CharField(blank=True, default='Swipe · Watch · Grow', max_length=140)),
                ('videos_subtitle', models.CharField(blank=True, default='Add short demo videos from Admin and they will show here automatically.', max_length=240)),
                ('reviews_title', models.CharField(blank=True, default='Google Play Reviews', max_length=140)),
                ('reviews_subtitle', models.CharField(blank=True, default='What customers say about Billentra', max_length=240)),
                ('cta_title', models.CharField(blank=True, default='Get started with Billentra', max_length=200)),
                ('cta_subtitle', models.TextField(blank=True, default='Join thousands of businesses using Billentra for faster invoicing, easier ledger tracking, and better financial management.')),
                ('support_title', models.CharField(blank=True, default='Contact Billentra', max_length=160)),
                ('support_subtitle', models.CharField(blank=True, default='Call, email, or send a message — we usually respond within 24 hours.', max_length=240)),
                ('support_phone', models.CharField(blank=True, default='+91 95557 33478', max_length=40)),
                ('support_email', models.EmailField(blank=True, default='support@billentra.com', max_length=254)),
                ('support_address', models.CharField(blank=True, default='Station Road, Basti, Uttar Pradesh 272002', max_length=240)),
                ('map_embed_url', models.URLField(blank=True, default='https://www.google.com/maps?q=Station%20Road%20Basti%20Uttar%20Pradesh%20272002&output=embed')),
                ('whatsapp_number', models.CharField(blank=True, default='919555733478', max_length=30)),
                ('whatsapp_default_message', models.CharField(blank=True, default='Hi, I need help with Billentra', max_length=240)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('show_clients', models.BooleanField(default=True)),
                ('show_usecases', models.BooleanField(default=True)),
                ('show_videos', models.BooleanField(default=True)),
                ('show_reviews', models.BooleanField(default=True)),
                ('show_download_popup', models.BooleanField(default=True)),
                ('show_social_bar', models.BooleanField(default=True)),
                ('show_whatsapp_widget', models.BooleanField(default=True)),
                ('show_chatbot_widget', models.BooleanField(default=False)),
                ('enable_websocket_chat', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Settings',
                'verbose_name_plural': 'Landing Page Settings',
            },
        ),
        migrations.CreateModel(
            name='LandingPricingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('free_state', models.CharField(choices=[('text', 'Text'), ('ok', '✔'), ('no', '✖'), ('trial', '⚠ Trial Only')], default='text', max_length=10)),
                ('free_text', models.CharField(blank=True, default='', max_length=200)),
                ('pro_state', models.CharField(choices=[('text', 'Text'), ('ok', '✔'), ('no', '✖'), ('trial', '⚠ Trial Only')], default='text', max_length=10)),
                ('pro_text', models.CharField(blank=True, default='', max_length=200)),
                ('pro_max_state', models.CharField(choices=[('text', 'Text'), ('ok', '✔'), ('no', '✖'), ('trial', '⚠ Trial Only')], default='text', max_length=10)),
                ('pro_max_text', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Landing Pricing Row',
                'verbose_name_plural': 'Landing Pricing Rows',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='LandingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='landing/reviews/')),
                ('source', models.CharField(blank=True, default='Google Play', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Landing Review',
                'verbose_name_plural': 'Landing Reviews',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/usecases/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Landing Use Case',
                'verbose_name_plural': 'Landing Use Cases',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
