from django.urls import path

from . import store_views

urlpatterns = [
    path("", store_views.store_index, name="store-index"),
    path("<slug:subdomain>/", store_views.store_home, name="store-home"),
    path("<slug:subdomain>/p/<slug:slug>/", store_views.store_product_detail, name="store-product-detail"),
    path("<slug:subdomain>/cart/", store_views.store_cart_view, name="store-cart"),
    path("<slug:subdomain>/cart/add/", store_views.store_cart_add, name="store-cart-add"),
    path("<slug:subdomain>/cart/update/", store_views.store_cart_update, name="store-cart-update"),
    path("<slug:subdomain>/cart/coupon/apply/", store_views.store_coupon_apply, name="store-coupon-apply"),
    path("<slug:subdomain>/cart/coupon/clear/", store_views.store_coupon_clear, name="store-coupon-clear"),
    path("<slug:subdomain>/cart/buy-now/", store_views.store_buy_now, name="store-buy-now"),
    path("<slug:subdomain>/wishlist/", store_views.store_wishlist_view, name="store-wishlist"),
    path("<slug:subdomain>/wishlist/toggle/", store_views.store_wishlist_toggle, name="store-wishlist-toggle"),
    path("<slug:subdomain>/checkout/", store_views.store_checkout, name="store-checkout"),
    path("<slug:subdomain>/pay/<uuid:token>/", store_views.store_payment_start, name="store-payment-start"),
    path("<slug:subdomain>/pay/<uuid:token>/demo/success/", store_views.store_payment_demo_success, name="store-payment-demo-success"),
    path("<slug:subdomain>/pay/<uuid:token>/demo/fail/", store_views.store_payment_demo_fail, name="store-payment-demo-fail"),
    path("<slug:subdomain>/location/", store_views.store_update_location, name="store-update-location"),
    path("<slug:subdomain>/_geo/reverse/", store_views.store_geo_reverse, name="store-geo-reverse"),
    path("<slug:subdomain>/_geo/search/", store_views.store_geo_search, name="store-geo-search"),
    path("<slug:subdomain>/_apps/lead-capture/", store_views.store_app_lead_capture, name="store-app-lead-capture"),
    path("<slug:subdomain>/track/<uuid:token>/", store_views.store_track, name="store-track"),
    path("<slug:subdomain>/me/orders/", store_views.store_me_orders, name="store-me-orders"),
    path("<slug:subdomain>/me/orders/<int:order_id>/", store_views.store_me_order_view, name="store-me-order-view"),

    # Vendor UI
    path("<slug:subdomain>/vendor/", store_views.vendor_dashboard, name="vendor-dashboard-ui"),
    path("<slug:subdomain>/vendor/settings/general/", store_views.vendor_settings_general, name="vendor-settings-general"),
    path("<slug:subdomain>/vendor/settings/plan/", store_views.vendor_settings_plan, name="vendor-settings-plan"),
    path("<slug:subdomain>/vendor/settings/billing/", store_views.vendor_settings_billing, name="vendor-settings-billing"),
    path("<slug:subdomain>/vendor/settings/users/", store_views.vendor_settings_users, name="vendor-settings-users"),
    path("<slug:subdomain>/vendor/settings/payments/", store_views.vendor_settings_payments, name="vendor-settings-payments"),
    path("<slug:subdomain>/vendor/settings/checkout/", store_views.vendor_settings_checkout, name="vendor-settings-checkout"),
    path(
        "<slug:subdomain>/vendor/settings/customer-accounts/",
        store_views.vendor_settings_customer_accounts,
        name="vendor-settings-customer-accounts",
    ),
    path("<slug:subdomain>/vendor/settings/shipping/", store_views.vendor_settings_shipping, name="vendor-settings-shipping"),
    path("<slug:subdomain>/vendor/settings/taxes/", store_views.vendor_settings_taxes, name="vendor-settings-taxes"),
    path("<slug:subdomain>/vendor/settings/locations/", store_views.vendor_settings_locations, name="vendor-settings-locations"),
    path("<slug:subdomain>/vendor/settings/markets/", store_views.vendor_settings_markets, name="vendor-settings-markets"),
    path("<slug:subdomain>/vendor/settings/apps/", store_views.vendor_settings_apps, name="vendor-settings-apps"),
    path(
        "<slug:subdomain>/vendor/settings/apps/shopify/connect/",
        store_views.vendor_shopify_connect_start,
        name="vendor-shopify-connect-start",
    ),
    path(
        "<slug:subdomain>/vendor/settings/apps/shopify/disconnect/",
        store_views.vendor_shopify_disconnect,
        name="vendor-shopify-disconnect",
    ),
    path("<slug:subdomain>/vendor/settings/sales-channels/", store_views.vendor_settings_sales_channels, name="vendor-settings-sales-channels"),
    path("<slug:subdomain>/vendor/settings/domains/", store_views.vendor_settings_domains, name="vendor-settings-domains"),
    path("<slug:subdomain>/vendor/settings/customer-events/", store_views.vendor_settings_customer_events, name="vendor-settings-customer-events"),
    path("<slug:subdomain>/vendor/settings/notifications/", store_views.vendor_settings_notifications, name="vendor-settings-notifications"),
    path("<slug:subdomain>/vendor/settings/metafields/", store_views.vendor_settings_metafields, name="vendor-settings-metafields"),

    # Vendor marketing hub
    path("<slug:subdomain>/vendor/marketing/campaigns/", store_views.vendor_marketing_campaigns, name="vendor-marketing-campaigns"),
    path(
        "<slug:subdomain>/vendor/marketing/campaigns/new/",
        store_views.vendor_marketing_campaign_create,
        name="vendor-marketing-campaign-create",
    ),
    path(
        "<slug:subdomain>/vendor/marketing/campaigns/<int:campaign_id>/",
        store_views.vendor_marketing_campaign_view,
        name="vendor-marketing-campaign-view",
    ),
    path(
        "<slug:subdomain>/vendor/marketing/campaigns/<int:campaign_id>/start/",
        store_views.vendor_marketing_campaign_start,
        name="vendor-marketing-campaign-start",
    ),
    path("<slug:subdomain>/vendor/marketing/creatives/", store_views.vendor_marketing_creatives, name="vendor-marketing-creatives"),
    path(
        "<slug:subdomain>/vendor/marketing/creatives/new/",
        store_views.vendor_marketing_creative_create,
        name="vendor-marketing-creative-create",
    ),
    path(
        "<slug:subdomain>/vendor/marketing/creatives/<int:creative_id>/delete/",
        store_views.vendor_marketing_creative_delete,
        name="vendor-marketing-creative-delete",
    ),
    path("<slug:subdomain>/vendor/marketing/leads/", store_views.vendor_marketing_leads, name="vendor-marketing-leads"),
    path(
        "<slug:subdomain>/vendor/marketing/leads/<int:lead_id>/",
        store_views.vendor_marketing_lead_view,
        name="vendor-marketing-lead-view",
    ),
    path(
        "<slug:subdomain>/vendor/marketing/leads/<int:lead_id>/update/",
        store_views.vendor_marketing_lead_update,
        name="vendor-marketing-lead-update",
    ),
    path(
        "<slug:subdomain>/vendor/marketing/leads/<int:lead_id>/send/",
        store_views.vendor_marketing_lead_send,
        name="vendor-marketing-lead-send",
    ),
    path("<slug:subdomain>/vendor/coupons/", store_views.vendor_coupons, name="vendor-coupons"),
    path("<slug:subdomain>/vendor/reports/orders.csv", store_views.vendor_orders_report_csv, name="vendor-orders-report-csv"),
    path("<slug:subdomain>/vendor/orders/", store_views.vendor_orders, name="vendor-orders"),
    path("<slug:subdomain>/vendor/products/", store_views.vendor_products, name="vendor-products"),
    path("<slug:subdomain>/vendor/products/bulk/", store_views.vendor_products_bulk_import, name="vendor-products-bulk-import"),
    path("<slug:subdomain>/vendor/products/<int:listing_id>/", store_views.vendor_product_edit, name="vendor-product-edit"),
    path(
        "<slug:subdomain>/vendor/products/<int:listing_id>/media/upload/",
        store_views.vendor_product_media_upload,
        name="vendor-product-media-upload",
    ),
    path(
        "<slug:subdomain>/vendor/products/<int:listing_id>/media/upload/images/",
        store_views.vendor_product_media_upload_images,
        name="vendor-product-media-upload-images",
    ),
    path(
        "<slug:subdomain>/vendor/products/<int:listing_id>/media/upload/videos/",
        store_views.vendor_product_media_upload_videos,
        name="vendor-product-media-upload-videos",
    ),
    path(
        "<slug:subdomain>/vendor/products/<int:listing_id>/media/<int:media_id>/delete/",
        store_views.vendor_product_media_delete,
        name="vendor-product-media-delete",
    ),
    # Vendor catalogs
    path("<slug:subdomain>/vendor/catalogs/", store_views.vendor_catalogs, name="vendor-catalogs"),
    path("<slug:subdomain>/vendor/catalogs/new/", store_views.vendor_catalog_create, name="vendor-catalog-create"),
    path("<slug:subdomain>/vendor/catalogs/<int:catalog_id>/", store_views.vendor_catalog_edit, name="vendor-catalog-edit"),
    path("<slug:subdomain>/vendor/catalogs/<int:catalog_id>/export/", store_views.vendor_catalog_export, name="vendor-catalog-export"),
    path("<slug:subdomain>/vendor/catalogs/<int:catalog_id>/import/", store_views.vendor_catalog_import, name="vendor-catalog-import"),
    path("<slug:subdomain>/vendor/catalogs/rollouts/", store_views.vendor_catalog_rollouts, name="vendor-catalog-rollouts"),
    path("<slug:subdomain>/vendor/catalogs/rollouts/new/", store_views.vendor_catalog_rollout_create, name="vendor-catalog-rollout-create"),
    path("<slug:subdomain>/vendor/catalogs/rollouts/<int:rollout_id>/", store_views.vendor_catalog_rollout_view, name="vendor-catalog-rollout-view"),
    path("<slug:subdomain>/vendor/catalogs/rollouts/run-now/", store_views.vendor_catalog_rollouts_run_now, name="vendor-catalog-rollouts-run-now"),

    # Vendor customers (Segments / Companies)
    path("<slug:subdomain>/vendor/customers/segments/", store_views.vendor_customer_segments, name="vendor-customer-segments"),
    path("<slug:subdomain>/vendor/customers/segments/new/", store_views.vendor_customer_segment_create, name="vendor-customer-segment-create"),
    path("<slug:subdomain>/vendor/customers/segments/<int:segment_id>/", store_views.vendor_customer_segment_view, name="vendor-customer-segment-view"),
    path("<slug:subdomain>/vendor/customers/companies/", store_views.vendor_customer_companies, name="vendor-customer-companies"),
    path("<slug:subdomain>/vendor/customers/companies/<int:company_id>/", store_views.vendor_customer_company_view, name="vendor-customer-company-view"),
    path("<slug:subdomain>/vendor/orders/<int:order_id>/", store_views.vendor_order_view, name="vendor-order-view"),
    path("<slug:subdomain>/vendor/orders/<int:order_id>/accept/", store_views.vendor_order_accept, name="vendor-order-accept"),
    path("<slug:subdomain>/vendor/orders/<int:order_id>/reject/", store_views.vendor_order_reject, name="vendor-order-reject"),
    path(
        "<slug:subdomain>/vendor/orders/<int:order_id>/sync-billing/",
        store_views.vendor_order_sync_billing,
        name="vendor-order-sync-billing",
    ),
    path(
        "<slug:subdomain>/vendor/orders/<int:order_id>/shipping/create/",
        store_views.vendor_order_shipping_create,
        name="vendor-order-shipping-create",
    ),
    path(
        "<slug:subdomain>/vendor/orders/<int:order_id>/shipping/pickup/",
        store_views.vendor_order_shipping_pickup,
        name="vendor-order-shipping-pickup",
    ),
    path(
        "<slug:subdomain>/vendor/orders/<int:order_id>/shipping/track/",
        store_views.vendor_order_shipping_track,
        name="vendor-order-shipping-track",
    ),
]
