# Generated by GPT-5.2 on 2026-03-02
import decimal

from django.db import migrations, models
from django.db.models import Sum
import django.db.models.deletion
import django.utils.timezone


def backfill_order_conversion(apps, schema_editor):
    Order = apps.get_model("commerce", "Order")
    OrderItem = apps.get_model("commerce", "OrderItem")

    for order in Order.objects.all().iterator():
        agg = OrderItem.objects.filter(order_id=order.id).aggregate(
            total=Sum("qty"),
            invoiced=Sum("invoiced_qty"),
        )
        total = agg.get("total") or 0
        invoiced = agg.get("invoiced") or decimal.Decimal("0.00")
        try:
            total_dec = decimal.Decimal(str(total)).quantize(decimal.Decimal("0.01"))
        except Exception:
            total_dec = decimal.Decimal("0.00")

        try:
            invoiced_dec = decimal.Decimal(str(invoiced)).quantize(decimal.Decimal("0.01"))
        except Exception:
            invoiced_dec = decimal.Decimal("0.00")

        if invoiced_dec <= decimal.Decimal("0.00"):
            status = "pending"
        elif invoiced_dec < total_dec:
            status = "partial"
        else:
            status = "completed"

        Order.objects.filter(id=order.id).update(
            total_qty=total_dec,
            invoiced_qty=invoiced_dec,
            conversion_status=status,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0019_syncedinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="conversion_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("partial", "Partial"), ("completed", "Completed")],
                db_index=True,
                default="pending",
                help_text="Order-to-voucher conversion status.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoiced_qty",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="order",
            name="total_qty",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="invoiced_qty",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_percent",
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=6),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="commerce.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="salesvoucher",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="salesvoucheritem",
            name="source_order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_voucher_items",
                to="commerce.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="salesvoucheritem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_voucher_items",
                to="commerce.warehouse",
            ),
        ),
        migrations.RunPython(backfill_order_conversion, migrations.RunPython.noop),
    ]
