# Generated by GPT-5.2 on 2026-03-02
import decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0020_order_to_voucher_autofill"),
        ("khataapp", "0009_companysettings_auto_sms_send"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quotation_number", models.CharField(blank=True, null=True, db_index=True, max_length=30, unique=True)),
                ("date", models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ("valid_till", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("verified", "Verified"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("converted", "Converted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "converted_order",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_from_quotations",
                        to="commerce.order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="khataapp.party",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations",
                        to="commerce.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("rate", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("tax", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=6)),
                ("discount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=14)),
                (
                    "product",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_items",
                        to="commerce.product",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.quotation",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_items",
                        to="commerce.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QuotationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=40)),
                ("from_status", models.CharField(blank=True, db_index=True, max_length=16)),
                ("to_status", models.CharField(blank=True, db_index=True, max_length=16)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("performed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="commerce.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["status", "date"], name="quote_status_date_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["party", "status"], name="quote_party_status_idx"),
        ),
        migrations.AddIndex(
            model_name="quotationitem",
            index=models.Index(fields=["quotation", "product"], name="quote_item_q_p_idx"),
        ),
        migrations.AddIndex(
            model_name="quotationauditlog",
            index=models.Index(fields=["quotation", "performed_at"], name="quote_audit_q_dt_idx"),
        ),
        migrations.AddField(
            model_name="order",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text="Source quotation (if this order was converted from a quotation).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="commerce.quotation",
            ),
        ),
    ]
