# Generated by Django 5.2.5 on 2026-03-07 15:01

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncqueue',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Desktop device ID (used to avoid ID collisions across devices).', max_length=64),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SyncedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('local_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'model_name', 'local_id'), name='uniq_synced_object_device_model_local')],
            },
        ),
        migrations.CreateModel(
            name='SyncMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('local_id', models.CharField(db_index=True, max_length=64)),
                ('cloud_id', models.CharField(db_index=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device_id', 'model_name', 'local_id'), name='uniq_sync_mapping_device_model_local')],
            },
        ),
    ]
