# Generated by Django 5.2.5 on 2026-03-13 13:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_product_image'),
        ('smart_bi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='festival_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='smart_bi.festivalcampaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='festival_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
