# Generated by Django 5.2.5 on 2026-03-14

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0025_order_festival_campaign_and_more"),
        ("whatsapp", "0002_multitenant_whatsapp_automation"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapporderinbox",
            name="whatsapp_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commerce_order_inbox",
                to="whatsapp.whatsappaccount",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="whatsapp_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commerce_sessions",
                to="whatsapp.whatsappaccount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="whatsappsession",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="whatsappsession",
            constraint=models.UniqueConstraint(
                condition=Q(("whatsapp_account__isnull", True)),
                fields=("owner", "mobile_number"),
                name="uniq_wa_sess_owner_mobile_noacc",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappsession",
            constraint=models.UniqueConstraint(
                condition=Q(("whatsapp_account__isnull", False)),
                fields=("owner", "whatsapp_account", "mobile_number"),
                name="uniq_wa_sess_owner_acc_mobile",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(fields=["owner", "whatsapp_account", "last_message_at"], name="wa_sess_owner_acc_dt_idx"),
        ),
    ]

