# Generated by Django 5.2.5 on 2026-05-10 08:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice_number', models.CharField(db_index=True, max_length=80)),
                ('invoice_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('invoice_type', models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('bill_of_supply', 'Bill of Supply'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note')], default='tax_invoice', max_length=30)),
                ('supply_type', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('export', 'Export'), ('sez', 'SEZ')], db_index=True, default='b2b', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('eway_required', 'E-Way Required'), ('eway_ready', 'E-Way Ready'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('seller_gstin', models.CharField(db_index=True, max_length=15)),
                ('seller_state_code', models.CharField(db_index=True, max_length=2)),
                ('place_of_supply_state_code', models.CharField(db_index=True, max_length=2)),
                ('reverse_charge', models.BooleanField(db_index=True, default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'tax_gst_invoices',
                'ordering': ('-invoice_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EWayBillRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('required', 'Required'), ('draft', 'Draft'), ('ready', 'Ready'), ('generated', 'Generated'), ('cancelled', 'Cancelled')], db_index=True, default='required', max_length=30)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=180)),
                ('transporter_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('transporter_doc_no', models.CharField(blank=True, default='', max_length=80)),
                ('transporter_doc_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=30)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('air', 'Air'), ('ship', 'Ship')], default='road', max_length=20)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('dispatch_address', models.TextField(blank=True, default='')),
                ('dispatch_pincode', models.CharField(blank=True, default='', max_length=8)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('delivery_pincode', models.CharField(blank=True, default='', max_length=8)),
                ('reason_for_transport', models.CharField(default='supply', max_length=40)),
                ('eway_ready_payload', models.JSONField(blank=True, default=dict)),
                ('eway_bill_no', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eway_bill', to='platform_tax.gstinvoice')),
            ],
            options={
                'db_table': 'tax_eway_bill_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GSTParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('transporter', 'Transporter')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('gstin', models.CharField(blank=True, db_index=True, default='', max_length=15)),
                ('pan', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('address', models.TextField(blank=True, default='')),
                ('pincode', models.CharField(blank=True, default='', max_length=8)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'tax_gst_parties',
            },
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gst_invoices', to='platform_tax.gstparty'),
        ),
        migrations.CreateModel(
            name='GSTReportSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('report_type', models.CharField(choices=[('sales_register', 'GST Sales Register'), ('purchase_register', 'GST Purchase Register'), ('tax_summary', 'Tax Summary'), ('hsn_summary', 'HSN Summary'), ('gstr1', 'GSTR-1'), ('gstr3b', 'GSTR-3B'), ('eway', 'E-Way Bill Report'), ('transporter', 'Transporter Report')], db_index=True, max_length=40)),
                ('period', models.CharField(db_index=True, max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_report_snapshots', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'tax_gst_report_snapshots',
            },
        ),
        migrations.CreateModel(
            name='GSTTaxSlab',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'tax_gst_slabs',
                'ordering': ('rate',),
                'unique_together': {('rate', 'cess_rate')},
            },
        ),
        migrations.CreateModel(
            name='HSNSACCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('code_type', models.CharField(choices=[('hsn', 'HSN'), ('sac', 'SAC')], db_index=True, max_length=8)),
                ('description', models.CharField(max_length=260)),
                ('is_goods', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tax_slab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hsn_sac_codes', to='platform_tax.gsttaxslab')),
            ],
            options={
                'db_table': 'tax_hsn_sac_codes',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='GSTInvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=260)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='platform_tax.gstinvoice')),
                ('hsn_sac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='platform_tax.hsnsaccode')),
            ],
            options={
                'db_table': 'tax_gst_invoice_lines',
            },
        ),
        migrations.CreateModel(
            name='PaymentQRProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=160)),
                ('upi_id', models.CharField(blank=True, default='', max_length=120)),
                ('bank_name', models.CharField(blank=True, default='', max_length=160)),
                ('account_name', models.CharField(blank=True, default='', max_length=180)),
                ('account_number', models.CharField(blank=True, default='', max_length=60)),
                ('ifsc', models.CharField(blank=True, default='', max_length=16)),
                ('payment_link', models.CharField(blank=True, default='', max_length=500)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'tax_payment_qr_profiles',
            },
        ),
        migrations.AddField(
            model_name='gstinvoice',
            name='payment_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='platform_tax.paymentqrprofile'),
        ),
        migrations.CreateModel(
            name='TaxAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='platform_tax.gstinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'tax_audit_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaxValidationIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('message', models.CharField(max_length=260)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='error', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='platform_tax.gstinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'tax_validation_issues',
            },
        ),
        migrations.AddIndex(
            model_name='gstparty',
            index=models.Index(fields=['tenant', 'party_type', 'gstin'], name='tax_gst_par_tenant__4d631c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gstreportsnapshot',
            unique_together={('tenant', 'report_type', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='hsnsaccode',
            unique_together={('code', 'code_type')},
        ),
        migrations.AddIndex(
            model_name='paymentqrprofile',
            index=models.Index(fields=['tenant', 'is_default'], name='tax_payment_tenant__d18957_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gstinvoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='taxvalidationissue',
            index=models.Index(fields=['tenant', 'severity', 'code'], name='tax_validat_tenant__f23123_idx'),
        ),
    ]
