# Generated by Django 5.2.5 on 2026-03-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_creative_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.CharField(default='auto', help_text='auto / hi / en / hi-en', max_length=16),
        ),
        migrations.AddField(
            model_name='campaign',
            name='optimize_goal',
            field=models.CharField(blank=True, default='', help_text='cpa / ctr / conversions', max_length=40),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pincodes',
            field=models.JSONField(blank=True, default=list, help_text='Hyperlocal targeting (list of pincodes)'),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('agent', 'Agent QR'), ('campaign', 'Campaign QR'), ('product', 'Product QR')], db_index=True, default='campaign', max_length=20)),
                ('target_url', models.URLField(blank=True, default='')),
                ('scan_count', models.IntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_qrcodes', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcodes', to='marketing.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='qr_kind_dt_idx'), models.Index(fields=['agent', 'created_at'], name='qr_agent_dt_idx')],
            },
        ),
    ]
