# Generated by Django 5.2.5 on 2026-04-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaign_ai_creative_url_campaign_budget_daily_and_more'),
        ('products', '0005_rename_products_pr_product_34d9b4_idx_products_pr_product_51cb22_idx'),
        ('vendors', '0006_alter_vendormarketingproviderconfig_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('reel', 'Reel/Video')], db_index=True, default='image', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('source_url', models.URLField(blank=True, default='')),
                ('template', models.CharField(blank=True, default='', help_text='Template name for future rendering.', max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_assets', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_assets', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'kind', 'created_at'], name='marketing_c_vendor__54bfb8_idx')],
            },
        ),
    ]
