# Generated by Django 5.2.5 on 2026-04-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_creativeasset'),
        ('vendors', '0006_alter_vendormarketingproviderconfig_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeasset',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creativeasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='creative_assets/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook Ads'), ('instagram', 'Instagram Ads'), ('google', 'Google Ads'), ('ott', 'OTT Ads')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='creativeasset',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('reel', 'Reel/Video'), ('gif', 'Reel GIF')], db_index=True, default='image', max_length=20),
        ),
        migrations.CreateModel(
            name='PaidAdRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook Ads'), ('instagram', 'Instagram Ads'), ('google', 'Google Ads'), ('ott', 'OTT Ads')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=140)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_runs', to='marketing.campaign')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_ad_runs', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['vendor', 'status', 'queued_at'], name='marketing_p_vendor__f29b1a_idx'), models.Index(fields=['channel', 'status', 'queued_at'], name='marketing_p_channel_06eb21_idx')],
            },
        ),
    ]
