# Generated by Django 5.2.5 on 2026-03-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.PositiveIntegerField(default=0)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, default='monthly', max_length=10)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'rank'],
                'indexes': [models.Index(fields=['period', 'computed_at'], name='performance_period_3a815c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], db_index=True, default='monthly', max_length=10)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='performance_user_id_e2c29c_idx')],
            },
        ),
    ]
