# Generated by Django 5.2.5 on 2026-03-19 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_loyaltyprogram_membershiptier_loyaltypoints_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Downline/upline hierarchy. Optional for backward compatibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Referral attribution. May be same as parent in simple setups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'SuperAdmin'), ('state_admin', 'StateAdmin'), ('district_admin', 'DistrictAdmin'), ('area_admin', 'AreaAdmin'), ('super_agent', 'SuperAgent'), ('agent', 'Agent'), ('customer', 'Customer')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user_profiles', to='location.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user_profiles', to='location.district'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user_profiles', to='location.pincode'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user_profiles', to='location.state'),
        ),
    ]
