from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saas", "0004_rename_saas_userpe_user_id_5bc5b7_idx_saas_userpe_user_id_3548a5_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(db_index=True, max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="apps", max_length=60)),
                ("color", models.CharField(blank=True, default="#2563EB", max_length=20)),
                ("web_url", models.CharField(blank=True, default="", max_length=240)),
                ("app_route", models.CharField(blank=True, default="", max_length=120)),
                ("api_namespace", models.CharField(blank=True, default="", max_length=120)),
                ("access_platforms", models.JSONField(blank=True, default=list)),
                ("required_permissions", models.JSONField(blank=True, default=list)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField(db_index=True, default=100)),
                ("is_core", models.BooleanField(db_index=True, default=False)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["order", "name"]},
        ),
        migrations.CreateModel(
            name="ThemeConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(db_index=True, max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("brand_name", models.CharField(blank=True, default="Billentra", max_length=120)),
                ("logo_url", models.CharField(blank=True, default="", max_length=300)),
                ("primary", models.CharField(default="#0F766E", max_length=20)),
                ("secondary", models.CharField(default="#2563EB", max_length=20)),
                ("accent", models.CharField(default="#F59E0B", max_length=20)),
                ("surface", models.CharField(default="#F8FAFC", max_length=20)),
                ("dark_surface", models.CharField(default="#0B1120", max_length=20)),
                ("radius", models.PositiveSmallIntegerField(default=8)),
                ("density", models.CharField(default="comfortable", max_length=20)),
                ("typography", models.JSONField(blank=True, default=dict)),
                ("platform_overrides", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-is_default", "name"]},
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(db_index=True, max_length=120)),
                ("target", models.CharField(blank=True, default="", max_length=180)),
                ("platform", models.CharField(blank=True, default="", max_length=30)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enterprise_audit_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(db_index=True, max_length=120)),
                ("platform", models.CharField(blank=True, default="", max_length=30)),
                ("app_version", models.CharField(blank=True, default="", max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enterprise_device_sessions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PermissionTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(db_index=True, max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("permission_keys", models.JSONField(blank=True, default=list)),
                ("platform_access", models.JSONField(blank=True, default=dict)),
                ("is_system", models.BooleanField(db_index=True, default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enterprise_templates", to="saas.roletemplate")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(db_index=True, max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("landing_route", models.CharField(blank=True, default="", max_length=160)),
                ("platform", models.CharField(blank=True, default="web", max_length=30)),
                ("module_keys", models.JSONField(blank=True, default=list)),
                ("menu_schema", models.JSONField(blank=True, default=list)),
                ("layout_schema", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspaces", to="saas.roletemplate")),
            ],
            options={"ordering": ["order", "name"]},
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(db_index=True, max_length=80)),
                ("title", models.CharField(max_length=140)),
                ("widget_type", models.CharField(choices=[("metric", "Metric"), ("chart", "Chart"), ("table", "Table"), ("status", "Status"), ("actions", "Actions")], default="metric", max_length=20)),
                ("permission_key", models.CharField(blank=True, default="", max_length=120)),
                ("data_source", models.CharField(blank=True, default="", max_length=160)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField(db_index=True, default=100)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("module", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="widgets", to="enterprise_control.dynamicmodule")),
                ("workspace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="widgets", to="enterprise_control.workspace")),
            ],
            options={"ordering": ["order", "title"], "unique_together": {("workspace", "key")}},
        ),
        migrations.CreateModel(
            name="UserWorkspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform_overrides", models.JSONField(blank=True, default=dict)),
                ("module_overrides", models.JSONField(blank=True, default=dict)),
                ("dashboard_overrides", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_user_workspaces", to="saas.roletemplate")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="enterprise_workspace", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_users", to="enterprise_control.workspace")),
            ],
        ),
        migrations.AddIndex(model_name="dynamicmodule", index=models.Index(fields=["is_enabled", "order"], name="enterprise__is_enab_5b6f23_idx")),
        migrations.AddIndex(model_name="auditlog", index=models.Index(fields=["action", "created_at"], name="enterprise__action_795bba_idx")),
        migrations.AlterUniqueTogether(name="devicesession", unique_together={("user", "device_id")}),
        migrations.AddIndex(model_name="devicesession", index=models.Index(fields=["user", "is_active"], name="enterprise__user_id_5ceb54_idx")),
        migrations.AddIndex(model_name="userworkspace", index=models.Index(fields=["role"], name="enterprise__role_id_472169_idx")),
    ]
