# Generated by Django 5.2.5 on 2026-05-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_control', '0002_dynamic_ui_builders'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dynamicbutton',
            new_name='enterprise__is_enab_38db4c_idx',
            old_name='enterprise__is_enab_ba1c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='dynamicmenuitem',
            new_name='enterprise__parent__1c67cc_idx',
            old_name='enterprise__parent__8f1f3d_idx',
        ),
    ]
