# Generated by Django 5.2.5 on 2026-05-24 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_control', '0003_rename_enterprise__is_enab_ba1c8d_idx_enterprise__is_enab_38db4c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('endpoint', models.CharField(db_index=True, max_length=260)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], db_index=True, default='GET', max_length=10)),
                ('module', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('created', 'Created'), ('connected', 'Connected'), ('used', 'Used In App'), ('not_connected', 'Not Connected'), ('failed', 'Failed'), ('pending', 'Pending'), ('tested', 'Tested'), ('active', 'Active'), ('partial', 'Partial'), ('missing', 'Missing'), ('syncing', 'Syncing')], db_index=True, default='created', max_length=30)),
                ('connected_apps', models.JSONField(blank=True, default=list)),
                ('permission_keys', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(blank=True, default='v1', max_length=40)),
                ('auth_required', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(blank=True, db_index=True, default='manual', max_length=40)),
                ('last_usage_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_response_time_ms', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Registry',
                'verbose_name_plural': 'API Registry',
                'ordering': ['module', 'endpoint', 'method'],
                'unique_together': {('endpoint', 'method')},
            },
        ),
        migrations.CreateModel(
            name='APITestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('response_text', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveIntegerField(db_index=True, default=0)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('auth_status', models.CharField(blank=True, default='', max_length=40)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_test_logs', to=settings.AUTH_USER_MODEL)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_logs', to='enterprise_control.apiregistry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppFeatureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.SlugField(max_length=120, unique=True)),
                ('feature_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('required_apis', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('missing', 'Missing'), ('partial', 'Partial'), ('pending', 'Pending'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_apis', models.ManyToManyField(blank=True, related_name='feature_mappings', to='enterprise_control.apiregistry')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_mappings', to='enterprise_control.dynamicmodule')),
            ],
            options={
                'ordering': ['feature_name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Settings'), ('api', 'API Settings'), ('jwt', 'JWT Settings'), ('app', 'App Settings'), ('mobile', 'Mobile Settings'), ('pos', 'POS Settings'), ('kiosk', 'Kiosk Settings'), ('branding', 'Branding Settings'), ('smtp', 'SMTP Settings'), ('whatsapp', 'WhatsApp Settings'), ('sms', 'SMS Settings'), ('ai', 'AI Settings'), ('security', 'Security Settings'), ('device', 'Device Settings')], db_index=True, max_length=40)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('url', 'URL'), ('secret', 'Secret')], default='string', max_length=20)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('platform_access', models.JSONField(blank=True, default=list)),
                ('is_secret', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_control_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='enterprise__categor_2c5934_idx')],
            },
        ),
    ]
