# Generated by Django 5.2.5 on 2026-05-09 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
        ('platform_identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservabilityEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('request', 'Request'), ('trace', 'Trace'), ('audit', 'Audit'), ('performance', 'Performance'), ('slow_query', 'Slow Query'), ('health', 'Health'), ('error', 'Error')], db_index=True, max_length=40)),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('name', models.CharField(db_index=True, max_length=220)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(db_index=True, default='info', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observability_events', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'platform_core_observability_events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BackgroundJobDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('task_path', models.CharField(max_length=260)),
                ('queue', models.CharField(choices=[('default', 'Default'), ('notifications', 'Notifications'), ('reports', 'Reports'), ('ai', 'AI'), ('ocr', 'OCR'), ('exports', 'Exports'), ('integrations', 'Integrations')], db_index=True, default='default', max_length=40)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'platform_core_background_jobs',
                'ordering': ('queue', 'name'),
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CommandEnvelope',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(db_index=True, max_length=180)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_commands', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_envelopes', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'platform_core_command_envelopes',
                'indexes': [models.Index(fields=['tenant', 'command_type', 'created_at'], name='platform_co_tenant__5b369f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('endpoint_type', models.CharField(choices=[('webhook', 'Webhook'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('api', 'API'), ('analytics', 'Analytics'), ('ai', 'AI')], db_index=True, max_length=40)),
                ('target_url', models.CharField(blank=True, default='', max_length=500)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('rate_limit', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'platform_core_integration_endpoints',
                'ordering': ('endpoint_type', 'name'),
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PolicyDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('policy_type', models.CharField(choices=[('role', 'Role'), ('field', 'Field'), ('tenant', 'Tenant'), ('pricing', 'Pricing'), ('workflow', 'Workflow'), ('tax', 'Tax'), ('approval', 'Approval')], db_index=True, max_length=40)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('effect', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'platform_core_policies',
                'ordering': ('policy_type', 'priority', 'name'),
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='QueryDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('query_type', models.CharField(db_index=True, default='read_model', max_length=80)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('projection', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('permission_key', models.CharField(blank=True, default='', max_length=180)),
                ('cache_seconds', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'platform_core_query_definitions',
                'ordering': ('name',),
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=220)),
                ('rule_type', models.CharField(choices=[('business', 'Business'), ('pricing', 'Pricing'), ('tax', 'Tax'), ('approval', 'Approval'), ('automation', 'Automation'), ('validation', 'Validation')], db_index=True, max_length=40)),
                ('when', models.JSONField(blank=True, default=dict)),
                ('then', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='platform_identity.tenant')),
            ],
            options={
                'db_table': 'platform_core_rules',
                'ordering': ('rule_type', 'priority', 'name'),
                'unique_together': {('tenant', 'key')},
            },
        ),
    ]
