# Generated by GPT-5.2 on 2026-03-01
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("khataapp", "0008_transaction_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="auto_sms_send",
            field=models.BooleanField(default=True),
        ),
    ]

