# Generated by Django 5.2.5 on 2026-03-13 14:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('khataapp', '0010_party_credit_score_fields_and_reminderlog_invoice_tone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('coins_reward', models.PositiveIntegerField(default=0)),
                ('points_reward', models.PositiveIntegerField(default=0)),
                ('cashback_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_task_definitions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EngineControlPanelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('enable_rewards', models.BooleanField(default=True)),
                ('enable_referrals', models.BooleanField(default=True)),
                ('enable_payment_commission', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_loyalty', models.BooleanField(default=True)),
                ('enable_daily_tasks', models.BooleanField(default=True)),
                ('enable_analytics', models.BooleanField(default=True)),
                ('invoice_reward_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Nominal rewards rate (percent of invoice amount) used to derive coins/points.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('gst_invoice_bonus_points', models.PositiveIntegerField(default=10)),
                ('nongst_invoice_bonus_points', models.PositiveIntegerField(default=5)),
                ('payment_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Commission percent on successful payment receipts (for earnings dashboards).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('min_company_share_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('max_user_reward_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'engine_control_panel_settings',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.BigIntegerField(default=0)),
                ('cashback_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='khataapp.party')),
            ],
            options={
                'db_table': 'loyalty_accounts',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('transaction', 'Transaction'), ('invoice', 'Invoice'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('points_delta', models.BigIntegerField(default=0)),
                ('cashback_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='khataapp.loyaltyaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_records',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RewardLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('referral', 'Referral'), ('task', 'Daily Task'), ('loyalty', 'Loyalty'), ('storage', 'Storage'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('coins_delta', models.BigIntegerField(default=0)),
                ('points_delta', models.BigIntegerField(default=0)),
                ('amount_reference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessGrowthEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rewards', models.PositiveBigIntegerField(default=0, help_text='Total reward coins earned (lifetime).')),
                ('reward_points', models.PositiveBigIntegerField(default=0, help_text='Total reward points (lifetime).')),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('whatsapp_credits', models.PositiveIntegerField(default=0)),
                ('loyalty_points', models.PositiveBigIntegerField(default=0)),
                ('daily_task_streak', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('last_reward_update', models.DateTimeField(blank=True, null=True)),
                ('plan_locked_features', models.JSONField(blank=True, default=list)),
                ('storage_used', models.BigIntegerField(default=0)),
                ('analytics_snapshot', models.JSONField(blank=True, default=dict)),
                ('admin_profit_formula', models.JSONField(blank=True, default=dict)),
                ('referral_code', models.CharField(blank=True, default='', max_length=24, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_growth_engine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_growth_engine',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='bge_owner_upd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_completions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='khataapp.dailytaskdefinition')),
            ],
            options={
                'db_table': 'daily_task_completions',
                'ordering': ['-day', '-completed_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'day'], name='dtc_owner_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'task', 'day'), name='uniq_daily_task_owner_task_day')],
            },
        ),
        migrations.CreateModel(
            name='EngineEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flow', 'Flow'), ('audit', 'Audit')], db_index=True, default='flow', max_length=10)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('event_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('message', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_actor_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'engine_event_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'category', 'created_at'], name='englog_owner_cat_dt_idx'), models.Index(fields=['owner', 'level', 'created_at'], name='englog_owner_lvl_dt_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='loyaltyaccount',
            index=models.Index(fields=['owner', '-updated_at'], name='loy_owner_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyledgerentry',
            index=models.Index(fields=['owner', 'source', 'created_at'], name='loy_owner_src_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrecord',
            index=models.Index(fields=['referrer', 'status', 'created_at'], name='ref_ref_st_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralrecord',
            constraint=models.UniqueConstraint(fields=('referrer', 'referred'), name='uniq_referrer_referred'),
        ),
        migrations.AddIndex(
            model_name='rewardledgerentry',
            index=models.Index(fields=['owner', 'source', 'created_at'], name='rew_owner_src_dt_idx'),
        ),
    ]
