# Generated by Django 5.2.5 on 2026-03-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khataapp', '0011_business_growth_engine'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='location.pincode'),
        ),
        migrations.AddField(
            model_name='party',
            name='pincode_text',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
