# Generated by Django 5.2.5 on 2026-05-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfcheckout', '0004_alter_kioskevent_event_type'),
        ('selfcheckout', '0004_support_theme_idle'),
    ]

    operations = [
    ]
