# Generated by Django 5.2.5 on 2026-05-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfcheckout', '0005_merge_20260513_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskevent',
            name='event_type',
            field=models.CharField(choices=[('scan', 'Scan'), ('rfid', 'RFID'), ('voice', 'Voice'), ('coupon', 'Coupon'), ('payment', 'Payment'), ('fraud', 'Fraud'), ('health', 'Health'), ('assistant', 'Assistant'), ('customer', 'Customer'), ('support', 'Support'), ('theme', 'Theme'), ('idle', 'Idle')], db_index=True, max_length=20),
        ),
    ]
