# Generated by Django 5.2.5 on 2026-05-17 08:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_whatsapp_account_links'),
        ('selfcheckout', '0006_alter_kioskevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('media_url', models.URLField(blank=True, default='')),
                ('badge', models.CharField(blank=True, default='Flash Sale', max_length=40)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_checkout_promo_media', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_checkout_promo_media', to='commerce.product')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('coupon_code', models.CharField(default='LUCKY25', max_length=40)),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10)),
                ('probability', models.PositiveSmallIntegerField(default=35)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_checkout_reward_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(db_index=True, default='coupon', max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=40)),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drops', to='selfcheckout.rewardcampaign')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_drops', to='selfcheckout.checkoutsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KioskInteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_id', models.CharField(db_index=True, max_length=40)),
                ('kind', models.CharField(choices=[('click', 'Click'), ('touch', 'Touch'), ('hover', 'Hover'), ('add', 'Add To Cart'), ('abandon', 'Abandonment')], db_index=True, max_length=20)),
                ('area', models.CharField(db_index=True, max_length=80)),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('intensity', models.PositiveSmallIntegerField(default=1)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_checkout_interactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_checkout_interactions', to='commerce.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='selfcheckout.checkoutsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'kiosk_id', 'created_at'], name='selfco_ix_owner_kiosk_dt'), models.Index(fields=['kind', 'area', 'created_at'], name='selfco_ix_kind_area_dt')],
            },
        ),
        migrations.CreateModel(
            name='MobileContinueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=80, unique=True)),
                ('device_label', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_checkout_mobile_sessions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_continue_sessions', to='selfcheckout.checkoutsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'is_active', 'expires_at'], name='selfco_mob_owner_active_exp')],
            },
        ),
    ]
