# Generated by Django 5.2.5 on 2026-04-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_user_permission_override'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpermissiongraph',
            new_name='saas_userpe_user_id_3548a5_idx',
            old_name='saas_userpe_user_id_5bc5b7_idx',
        ),
        migrations.RenameIndex(
            model_name='userpermissionoverride',
            new_name='saas_userpe_user_id_84d6a4_idx',
            old_name='saas_userpe_user_id_39cf18_idx',
        ),
    ]
