# Generated by Django 5.2.5 on 2026-03-10 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ocr_invoices/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('reference_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ocr_ok', 'OCR OK'), ('parsed', 'Parsed'), ('created', 'Purchase Created'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_invoice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_invoice_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='ocr_owner_dt_idx'), models.Index(fields=['owner', 'status', 'created_at'], name='ocr_owner_st_dt_idx')],
            },
        ),
    ]
