# Generated by Django 5.2.5 on 2026-03-13 13:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0024_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='draft', max_length=10)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='festival_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'festival_campaign',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FestivalCampaignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_products', to='smart_bi.festivalcampaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_product_links', to='commerce.product')),
            ],
            options={
                'db_table': 'festival_products',
            },
        ),
        migrations.AddField(
            model_name='festivalcampaign',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='festival_campaigns', through='smart_bi.FestivalCampaignProduct', to='commerce.product'),
        ),
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('outstanding_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('stock_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('health_score', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_metrics',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['owner', '-date'], name='bizm_owner_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'date'), name='uniq_business_metrics_owner_date')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=2, help_text='Similarity score (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duplicate_invoice_logs', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_logs', to='commerce.invoice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_invoice_logs', to=settings.AUTH_USER_MODEL)),
                ('possible_duplicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_duplicate_logs', to='commerce.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='dup_inv_owner_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateInvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('window_minutes', models.PositiveIntegerField(default=60, help_text='Detection window in minutes (e.g. 60 for 1 hour).')),
                ('strict_mode', models.BooleanField(default=False, help_text='Strict mode flags only exact matches; soft mode uses similarity threshold.')),
                ('similarity_threshold', models.DecimalField(decimal_places=2, default=Decimal('90.00'), help_text='Similarity % above which invoices are flagged as possible duplicates.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_invoice_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duplicate Invoice Setting',
                'verbose_name_plural': 'Duplicate Invoice Settings',
                'constraints': [models.UniqueConstraint(fields=('owner',), name='uniq_dup_invoice_settings_owner')],
            },
        ),
        migrations.AddConstraint(
            model_name='festivalcampaignproduct',
            constraint=models.UniqueConstraint(fields=('campaign', 'product'), name='uniq_festival_campaign_product'),
        ),
        migrations.AddIndex(
            model_name='festivalcampaign',
            index=models.Index(fields=['owner', 'status', 'start_date', 'end_date'], name='fest_owner_active_idx'),
        ),
    ]
