# Generated by Django 5.2.5 on 2026-03-17 07:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_whatsapp_account_links'),
        ('khataapp', '0011_business_growth_engine'),
        ('smart_bi', '0002_fraudalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessmetric',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='duplicateinvoicelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='duplicateinvoicesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='festivalcampaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fraudalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='businessmetric',
            name='bizm_owner_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='duplicateinvoicelog',
            name='dup_inv_owner_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='festivalcampaign',
            name='fest_owner_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='fraudalert',
            name='fraud_owner_kind_dt_idx',
        ),
        migrations.RemoveField(
            model_name='festivalcampaign',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='reference_type',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='fraudalert',
            name='score',
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='alert_type',
            field=models.CharField(choices=[('high_amount', 'High Amount'), ('duplicate', 'Duplicate Transaction'), ('sudden_activity', 'Sudden Activity'), ('credit_risk', 'Credit Risk')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='khataapp.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khataapp.transaction'),
        ),
        migrations.AlterField(
            model_name='businessmetric',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='businessmetric',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='businessmetric',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duplicateinvoicelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='duplicateinvoicelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dup_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duplicateinvoicelog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_logs_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duplicateinvoicelog',
            name='similarity_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='duplicateinvoicesettings',
            name='similarity_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='duplicateinvoicesettings',
            name='strict_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='duplicateinvoicesettings',
            name='window_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='festivalcampaign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='festivalcampaign',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='festivalcampaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='festivalcampaign',
            name='products',
            field=models.ManyToManyField(blank=True, through='smart_bi.FestivalCampaignProduct', to='commerce.product'),
        ),
        migrations.AlterField(
            model_name='festivalcampaign',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='festivalcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='festivalcampaignproduct',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_bi.festivalcampaign'),
        ),
        migrations.AlterField(
            model_name='festivalcampaignproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='businessmetric',
            table=None,
        ),
        migrations.AlterModelTable(
            name='festivalcampaign',
            table=None,
        ),
        migrations.AlterModelTable(
            name='festivalcampaignproduct',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fraudalert',
            table=None,
        ),
    ]
