# Generated by Codex on 2026-04-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                (
                    "subdomain",
                    models.SlugField(
                        db_index=True,
                        help_text="Store subdomain like 'acme' for acme.yourdomain.com",
                        max_length=63,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        help_text="Primary account owning this vendor/store.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_vendors",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={"indexes": [models.Index(fields=["subdomain", "is_active"], name="vendors_ven_subdoma_6684c7_idx")]},
        ),
        migrations.CreateModel(
            name="VendorMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("owner", "Owner"), ("staff", "Staff")], db_index=True, default="staff", max_length=20)),
                ("department", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vendor_memberships", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="vendors.vendor"),
                ),
            ],
            options={
                "unique_together": {("vendor", "user")},
                "indexes": [models.Index(fields=["vendor", "role", "is_active"], name="vendors_ven_vendor__6b3f64_idx")],
            },
        ),
        migrations.CreateModel(
            name="VendorPaymentGatewayConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("razorpay", "Razorpay"), ("paytm", "Paytm"), ("stripe", "Stripe")], db_index=True, max_length=30)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_gateways", to="vendors.vendor"),
                ),
            ],
            options={
                "unique_together": {("vendor", "provider")},
                "indexes": [models.Index(fields=["vendor", "provider", "is_active"], name="vendors_ven_vendor__0c6b02_idx")],
            },
        ),
        migrations.CreateModel(
            name="VendorShippingProviderConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("delhivery", "Delhivery"), ("shiprocket", "Shiprocket"), ("bluedart", "BlueDart")], db_index=True, max_length=30)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shipping_providers", to="vendors.vendor"),
                ),
            ],
            options={
                "unique_together": {("vendor", "provider")},
                "indexes": [models.Index(fields=["vendor", "provider", "is_active"], name="vendors_ven_vendor__09b8f3_idx")],
            },
        ),
        migrations.CreateModel(
            name="VendorWarehouse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vendor_warehouses", to="vendors.vendor"),
                ),
                (
                    "warehouse",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="warehouse_vendors", to="warehouse.warehouse"),
                ),
            ],
            options={
                "unique_together": {("vendor", "warehouse")},
                "indexes": [models.Index(fields=["vendor", "is_active"], name="vendors_ven_vendor__b41f27_idx")],
            },
        ),
        migrations.AddField(
            model_name="vendor",
            name="warehouses",
            field=models.ManyToManyField(blank=True, related_name="vendors", through="vendors.VendorWarehouse", to="warehouse.warehouse"),
        ),
    ]

