# Generated by Django 5.2.5 on 2026-04-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorstoresettings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendor',
            new_name='vendors_ven_subdoma_a835ba_idx',
            old_name='vendors_ven_subdoma_6684c7_idx',
        ),
        migrations.RenameIndex(
            model_name='vendormembership',
            new_name='vendors_ven_vendor__8b2c34_idx',
            old_name='vendors_ven_vendor__6b3f64_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorpaymentgatewayconfig',
            new_name='vendors_ven_vendor__cdc482_idx',
            old_name='vendors_ven_vendor__0c6b02_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorshippingproviderconfig',
            new_name='vendors_ven_vendor__910cca_idx',
            old_name='vendors_ven_vendor__09b8f3_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorwarehouse',
            new_name='vendors_ven_vendor__0b4a28_idx',
            old_name='vendors_ven_vendor__b41f27_idx',
        ),
    ]
