# Generated by Django 5.2.5 on 2026-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_rename_vendors_ven_subdoma_6684c7_idx_vendors_ven_subdoma_a835ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstoresettings',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
