# Generated by Django 5.2.5 on 2026-04-22 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorstoresettings_settings_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMarketingProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('influencer', 'Influencer')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_providers', to='vendors.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor', 'provider', 'is_active'], name='vendors_ven_vendor__21895e_idx')],
                'unique_together': {('vendor', 'provider')},
            },
        ),
    ]
