# Generated by Django 5.2.5 on 2026-04-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendormarketingproviderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormarketingproviderconfig',
            name='provider',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('ott', 'OTT Ads'), ('influencer', 'Influencer')], db_index=True, max_length=30),
        ),
    ]
