# Generated by Django 5.2.5 on 2026-04-22 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_rename_storefront__vendor__coupon_idx_storefront__vendor__d025d3_idx'),
        ('vendors', '0006_alter_vendormarketingproviderconfig_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('markets_json', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(blank=True, default='INR', max_length=8)),
                ('price_adjustment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_adjustment_direction', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='decrease', max_length=16)),
                ('include_compare_at_price', models.BooleanField(default=False)),
                ('auto_include_new_products', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorCatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('include', 'Included'), ('exclude', 'Excluded')], db_index=True, default='include', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendors.vendorcatalog')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='storefront.vendorproductlisting')),
            ],
        ),
        migrations.AddIndex(
            model_name='vendorcatalog',
            index=models.Index(fields=['vendor', 'is_active', 'updated_at'], name='vendors_ven_vendor__2b0b60_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcatalogproduct',
            index=models.Index(fields=['catalog', 'mode', 'created_at'], name='vendors_ven_catalog_761bc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorcatalogproduct',
            unique_together={('catalog', 'listing')},
        ),
    ]
