# Generated by Django 5.2.5 on 2026-04-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendorcatalog_vendorcatalogproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCatalogRollout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('markets_json', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revert_on_end', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollouts', to='vendors.vendorcatalog')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_rollouts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status', 'starts_at'], name='vendors_ven_vendor__f90f26_idx'), models.Index(fields=['vendor', 'status', 'ends_at'], name='vendors_ven_vendor__883d22_idx')],
            },
        ),
    ]
