# Generated by Django 5.2.5 on 2026-04-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorcustomercompany_vendorcustomercompanymember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Support'), ('analytics', 'Analytics'), ('shipping', 'Shipping'), ('payments', 'Payments'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('short_description', models.CharField(blank=True, default='', max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Static icon path or URL', max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_builtin', models.BooleanField(db_index=True, default=True)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='Optional schema for future UI generation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category', 'name'], name='vendors_mar_is_acti_7a52bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorAppInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_installed', models.BooleanField(db_index=True, default=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='vendors.marketplaceapp')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_installs', to='vendors.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor', 'is_enabled', 'updated_at'], name='vendors_ven_vendor__465fcd_idx')],
                'unique_together': {('vendor', 'app')},
            },
        ),
    ]
