# Generated by Django 5.2.5 on 2026-05-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_seed_marketplace_apps'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendorshopifyconnection',
            new_name='vendors_ven_shop_do_7ac1b1_idx',
            old_name='vendors_ven_shop_do_570e8b_idx',
        ),
    ]
