# Generated by Django 5.2.5 on 2026-03-14

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q

import whatsapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("khataapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("phone_number", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                (
                    "provider",
                    models.CharField(
                        choices=[("meta_cloud_api", "WhatsApp Cloud API (Official)"), ("web_gateway", "WhatsApp Web / QR Gateway")],
                        db_index=True,
                        default="meta_cloud_api",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disconnected", "Disconnected"),
                            ("connecting", "Connecting"),
                            ("connected", "Connected"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("meta_phone_number_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("meta_waba_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("meta_graph_version", models.CharField(blank=True, default="v20.0", max_length=16)),
                ("meta_access_token", whatsapp.fields.EncryptedTextField(blank=True, default="")),
                ("meta_app_secret", whatsapp.fields.EncryptedTextField(blank=True, default="")),
                ("meta_verify_token", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("gateway_base_url", models.CharField(blank=True, default="", max_length=255)),
                ("gateway_api_key", whatsapp.fields.EncryptedTextField(blank=True, default="")),
                ("gateway_session_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("webhook_secret", whatsapp.fields.EncryptedTextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_accounts",
                "ordering": ["-created_at", "-updated_at"],
                "indexes": [
                    models.Index(fields=["owner", "provider", "status"], name="wa_acc_owner_pr_st_idx"),
                    models.Index(fields=["provider", "status"], name="wa_acc_pr_st_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=~Q(("phone_number", "")),
                        fields=("owner", "phone_number"),
                        name="uniq_wa_account_owner_phone",
                    ),
                    models.UniqueConstraint(
                        condition=~Q(("meta_phone_number_id", "")),
                        fields=("meta_phone_number_id",),
                        name="uniq_wa_meta_phone_number_id",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qr_required", "QR Required"),
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("provider_session_id", models.CharField(blank=True, db_index=True, default="", max_length=160)),
                ("qr_payload", models.TextField(blank=True, default="")),
                ("last_qr_at", models.DateTimeField(blank=True, null=True)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="whatsapp.whatsappaccount",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_sessions",
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["account", "status"], name="wa_sess_acc_st_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(db_index=True, max_length=32)),
                ("display_name", models.CharField(blank=True, default="", max_length=120)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_customers",
                        to="khataapp.party",
                    ),
                ),
                (
                    "whatsapp_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="whatsapp.whatsappaccount",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_customers",
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "phone_number"], name="wa_cust_owner_phone_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(("whatsapp_account__isnull", True)),
                        fields=("owner", "phone_number"),
                        name="uniq_wa_customer_owner_phone_noacc",
                    ),
                    models.UniqueConstraint(
                        condition=Q(("whatsapp_account__isnull", False)),
                        fields=("owner", "whatsapp_account", "phone_number"),
                        name="uniq_wa_customer_owner_acc_phone",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="WhatsApp Bot", max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Bot"),
                            ("order", "Order Bot"),
                            ("payment", "Payment Bot"),
                            ("support", "Support Bot"),
                            ("lead", "Lead Generation Bot"),
                            ("appointment", "Appointment Booking Bot"),
                            ("survey", "Survey Bot"),
                            ("custom", "Custom Bot"),
                        ],
                        db_index=True,
                        default="order",
                        max_length=30,
                    ),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("auto_reply_enabled", models.BooleanField(db_index=True, default=True)),
                ("ai_fallback_enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_bots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whatsapp_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot",
                        to="whatsapp.whatsappaccount",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_bots",
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "kind", "is_enabled"], name="wa_bot_owner_kind_en_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(db_index=True, max_length=80)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("location", "Location"),
                            ("contact", "Contact"),
                        ],
                        db_index=True,
                        default="text",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("media_url", models.URLField(blank=True, default="")),
                ("filename", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="whatsapp.bot",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_bot_messages",
                "indexes": [
                    models.Index(fields=["bot", "message_type"], name="wa_bot_msg_bot_type_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("bot", "key"), name="uniq_wa_bot_msg_key"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BotFlow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword"),
                            ("menu_selection", "Menu Selection"),
                            ("button_click", "Button Click"),
                            ("cart_action", "Cart Action"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("order_status", "Order Status"),
                            ("broadcast_trigger", "Broadcast Trigger"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("trigger_value", models.CharField(blank=True, db_index=True, default="", max_length=140)),
                ("trigger_payload", models.JSONField(blank=True, default=dict)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="whatsapp.bot",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_bot_flows",
                "ordering": ["priority", "-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["bot", "is_active", "priority"], name="wa_flow_bot_act_pr_idx"),
                    models.Index(fields=["bot", "trigger_type", "trigger_value"], name="wa_flow_bot_trig_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BroadcastCampaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="Broadcast Campaign", max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all_customers", "All Customers"),
                            ("selected_customers", "Selected Customers"),
                            ("customer_tag", "Customer Tag"),
                            ("recent_buyers", "Recent Buyers"),
                            ("inactive_customers", "Inactive Customers"),
                        ],
                        db_index=True,
                        default="all_customers",
                        max_length=40,
                    ),
                ),
                ("target_payload", models.JSONField(blank=True, default=dict)),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("image", "Image"), ("document", "Document")],
                        db_index=True,
                        default="text",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("media_url", models.URLField(blank=True, default="")),
                ("scheduled_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "whatsapp_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="whatsapp.whatsappaccount",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_broadcast_campaigns",
                "ordering": ["-created_at", "-updated_at"],
                "indexes": [
                    models.Index(fields=["owner", "status", "scheduled_at"], name="wa_bc_owner_st_sched_idx"),
                    models.Index(fields=["whatsapp_account", "status"], name="wa_bc_acc_st_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_logs",
                to="whatsapp.customer",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="message_type",
            field=models.CharField(blank=True, db_index=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="provider_message_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="whatsapp_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_logs",
                to="whatsapp.whatsappaccount",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="body",
            field=whatsapp.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["whatsapp_account", "created_at"], name="wa_msg_acc_dt_idx"),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["provider_message_id"], name="wa_msg_provider_id_idx"),
        ),
    ]

