# Generated by Django 5.2.5 on 2026-03-14

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_multitenant_whatsapp_automation"),
        ("khataapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappaccount",
            name="quick_commerce_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="whatsappaccount",
            name="quick_delivery_radius_km",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="whatsappaccount",
            name="store_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="whatsappaccount",
            name="store_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="whatsappaccount",
            name="quick_assign_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_quick_accounts",
                to="khataapp.fieldagent",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_location_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_location_lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_location_lng",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name="BotTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=140)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Bot"),
                            ("order", "Order Bot"),
                            ("payment", "Payment Bot"),
                            ("support", "Support Bot"),
                            ("lead", "Lead Generation Bot"),
                            ("appointment", "Appointment Booking Bot"),
                            ("survey", "Survey Bot"),
                            ("custom", "Custom Bot"),
                        ],
                        db_index=True,
                        default="order",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "whatsapp_bot_templates",
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "kind", "updated_at"], name="wa_tpl_act_kind_dt_idx"),
                ],
            },
        ),
    ]

