# Generated by Django 5.2.5 on 2026-03-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_bot_templates_and_quick_commerce'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('whatsapp.whatsappmessage',),
        ),
    ]
