# Generated by Django 5.2.5 on 2026-03-15 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_bottemplate_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='visual_flow_node_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='visual_flow_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VisualFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_visual_flows', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_flows', to='whatsapp.whatsappaccount')),
            ],
            options={
                'db_table': 'whatsapp_visual_flows',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=80)),
                ('target_id', models.CharField(db_index=True, max_length=80)),
                ('condition_text', models.CharField(blank=True, default='', max_length=200)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='whatsapp.visualflow')),
            ],
            options={
                'db_table': 'whatsapp_visual_edges',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='active_visual_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.visualflow'),
        ),
        migrations.CreateModel(
            name='VisualNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=80)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('message', 'Message'), ('condition', 'Condition'), ('action', 'Action'), ('end', 'End')], db_index=True, max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('position_x', models.IntegerField(default=40)),
                ('position_y', models.IntegerField(default=40)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='whatsapp.visualflow')),
            ],
            options={
                'db_table': 'whatsapp_visual_nodes',
            },
        ),
        migrations.AddIndex(
            model_name='visualflow',
            index=models.Index(fields=['whatsapp_account', 'is_active', 'updated_at'], name='wa_vf_acc_act_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='visualflow',
            index=models.Index(fields=['owner', 'updated_at'], name='wa_vf_owner_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='visualflow',
            constraint=models.UniqueConstraint(fields=('whatsapp_account', 'name'), name='uniq_wa_vf_acc_name'),
        ),
        migrations.AddIndex(
            model_name='visualedge',
            index=models.Index(fields=['flow', 'source_id'], name='wa_vedge_flow_src_idx'),
        ),
        migrations.AddIndex(
            model_name='visualedge',
            index=models.Index(fields=['flow', 'is_default'], name='wa_vedge_flow_def_idx'),
        ),
        migrations.AddIndex(
            model_name='visualnode',
            index=models.Index(fields=['flow', 'node_type'], name='wa_vnode_flow_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='visualnode',
            constraint=models.UniqueConstraint(fields=('flow', 'node_id'), name='uniq_wa_vnode_flow_nodeid'),
        ),
    ]
