# Generated by Django 5.2.5 on 2026-03-15 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0006_customer_visual_flow_node_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppOperator",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("phone_number", models.CharField(db_index=True, max_length=32)),
                ("display_name", models.CharField(blank=True, default="", max_length=120)),
                ("role", models.CharField(choices=[("admin", "Admin"), ("staff", "Staff")], db_index=True, default="admin", max_length=16)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_operators", to=settings.AUTH_USER_MODEL)),
                ("whatsapp_account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operators", to="whatsapp.whatsappaccount")),
            ],
            options={
                "db_table": "whatsapp_operators",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="whatsappoperator",
            index=models.Index(fields=["whatsapp_account", "is_active", "updated_at"], name="wa_op_acc_act_dt_idx"),
        ),
        migrations.AddIndex(
            model_name="whatsappoperator",
            index=models.Index(fields=["owner", "is_active", "updated_at"], name="wa_op_owner_act_dt_idx"),
        ),
        migrations.AddConstraint(
            model_name="whatsappoperator",
            constraint=models.UniqueConstraint(fields=("whatsapp_account", "phone_number"), name="uniq_wa_op_acc_phone"),
        ),
    ]

