# Generated by Django 5.2.5 on 2026-03-19 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_settings', '0006_desktoprelease_android_apk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('whatsapp_gateway', 'WhatsApp Gateway'), ('whatsapp_meta', 'WhatsApp Cloud API (Meta)'), ('sms', 'SMS Gateway'), ('email_smtp', 'Email SMTP'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('bank_payout', 'Bank Payout API')], db_index=True, max_length=40)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='core_settings.companysettings')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_connections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'name', '-created_at'],
                'indexes': [models.Index(fields=['company', 'provider', 'is_active'], name='api_integra_company_177991_idx')],
            },
        ),
    ]
