# Generated by GPT-5.2 on 2026-03-01
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMSProviderSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("google", "Google")], default="google", max_length=30, unique=True)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("sender_id", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "SMS Provider Setting",
                "verbose_name_plural": "SMS Provider Settings",
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("template_type", models.CharField(choices=[("order", "Order"), ("invoice", "Invoice"), ("voucher", "Voucher"), ("billing", "Billing")], db_index=True, max_length=20)),
                ("message_text", models.TextField(help_text="Supports variables: {{name}}, {{amount}}, {{invoice_no}}, {{date}}")),
                ("image_url", models.URLField(blank=True, null=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["template_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mobile", models.CharField(db_index=True, max_length=30)),
                ("message", models.TextField()),
                ("status", models.CharField(choices=[("sent", "Sent"), ("failed", "Failed"), ("skipped", "Skipped")], db_index=True, default="sent", max_length=20)),
                ("response", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="logs", to="sms_center.smstemplate")),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]

