# Generated by Django 5.2.5 on 2026-03-10 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_intent', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('parsed', 'Parsed'), ('created', 'Entry Created'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('reference_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_commands',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='vc_owner_dt_idx'), models.Index(fields=['owner', 'status', 'created_at'], name='vc_owner_st_dt_idx')],
            },
        ),
    ]
