# Generated by Django 5.2.5 on 2026-03-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
        ('voice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('new_lead', 'New Lead'), ('inactive_lead', 'Lead Inactive'), ('manual', 'Manual')], db_index=True, default='new_lead', max_length=20)),
                ('language', models.CharField(default='auto', help_text='auto / hi / en / hi-en', max_length=12)),
                ('script_prompt', models.TextField(blank=True, default='', help_text='System prompt used for TTS/LLM generation')),
                ('response_text', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('recording_url', models.URLField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='twilio', max_length=20)),
                ('provider_call_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_calls', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'status', 'created_at'], name='vc_lead_status_idx'), models.Index(fields=['agent', 'created_at'], name='vc_agent_dt_idx')],
            },
        ),
    ]
