# Generated by Django 5.2.5 on 2026-05-10 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_workforce', '0003_businessnetworknode_employeewallet_gigtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicWorkforceApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_type', models.CharField(choices=[('employee', 'Employee'), ('remote', 'Remote Worker'), ('freelancer', 'Freelancer'), ('part_time', 'Part-time Worker'), ('delivery', 'Delivery Partner'), ('field', 'Field Agent'), ('partner', 'Partner'), ('franchise', 'Franchise'), ('reseller', 'Reseller'), ('agency', 'Agency')], db_index=True, max_length=30)),
                ('full_name', models.CharField(max_length=180)),
                ('mobile', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('role_interest', models.CharField(blank=True, default='', max_length=180)),
                ('experience_years', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skills', models.TextField(blank=True, default='')),
                ('resume', models.FileField(blank=True, null=True, upload_to='workforce/applications/resumes/')),
                ('interview_slot', models.CharField(blank=True, default='', max_length=120)),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('referral_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('source', models.CharField(blank=True, db_index=True, default='landing', max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('onboarded', 'Onboarded')], db_index=True, default='new', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'workforce_public_applications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['applicant_type', 'status', 'created_at'], name='workforce_p_applica_146bc9_idx'), models.Index(fields=['mobile', 'created_at'], name='workforce_p_mobile_62cf60_idx')],
            },
        ),
    ]
