# Generated by Django 5.2.5 on 2026-03-10 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-computed_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'computed_at'], name='aiins_owner_dt_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'key'), name='uniq_ai_insight_owner_key')],
            },
        ),
    ]
