# Generated by Django 5.2.5 on 2026-03-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supplierpricealert',
            new_name='procurement_owner_i_0e8034_idx',
            old_name='procurement_owner_i_4d1a75_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierpricealert',
            new_name='procurement_owner_i_a964f2_idx',
            old_name='procurement_owner_p_3f75cb_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierpricehistory',
            new_name='procurement_owner_i_e794f4_idx',
            old_name='procurement_owner_p_093421_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierpricehistory',
            new_name='procurement_owner_i_464ca7_idx',
            old_name='procurement_owner_s_2d34a6_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierproduct',
            new_name='procurement_owner_i_3ff04d_idx',
            old_name='procurement_owner_p_eb0186_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierproduct',
            new_name='procurement_owner_i_1274bd_idx',
            old_name='procurement_owner_s_3f199d_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierproduct',
            new_name='procurement_owner_i_cf4007_idx',
            old_name='procurement_owner_p_f8f445_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierrating',
            new_name='procurement_owner_i_52480a_idx',
            old_name='procurement_owner_s_66404c_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierrating',
            new_name='procurement_owner_i_49eef3_idx',
            old_name='procurement_owner_r_3ab57c_idx',
        ),
    ]
