# Generated by Django 5.2.5 on 2026-03-14 00:00

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_rename_procurement_owner_i_4d1a75_idx_procurement_owner_i_0e8034_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commerce", "0025_order_festival_campaign_and_more"),
        ("khataapp", "0011_business_growth_engine"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITrainingLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("product_match", "Product Match"), ("product_match_correction", "Product Match Correction"), ("unit_conversion_edit", "Unit Conversion Edit"), ("supplier_template_update", "Supplier Template Update"), ("draft_approved", "Draft Approved"), ("draft_rejected", "Draft Rejected"), ("auto_approved", "Auto Approved"), ("validation_warning", "Validation Warning")], max_length=40, db_index=True)),
                ("reference_type", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("reference_id", models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_training_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_training_logs",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "event_type", "created_at"], name="ailog_owner_tp_dt_idx"),
                    models.Index(fields=["reference_type", "reference_id"], name="ailog_ref_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("ocr_scan", "OCR Scan"), ("whatsapp", "WhatsApp"), ("email", "Email"), ("portal", "Supplier Portal"), ("voice", "Voice"), ("excel", "Excel"), ("pdf", "PDF"), ("api", "Supplier ERP/API"), ("manual", "Manual Upload")], db_index=True, max_length=20)),
                ("external_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("file", models.FileField(blank=True, null=True, upload_to="invoice_sources/")),
                ("content_type", models.CharField(blank=True, default="", max_length=120)),
                ("extracted_text", models.TextField(blank=True, default="")),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("received", "Received"), ("extracted", "Extracted"), ("drafted", "Draft Created"), ("processed", "Processed"), ("failed", "Failed")], db_index=True, default="received", max_length=20)),
                ("error", models.TextField(blank=True, default="")),
                ("reference_type", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("reference_id", models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_sources",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "created_at"], name="invsrc_owner_dt_idx"),
                    models.Index(fields=["owner", "source_type", "created_at"], name="invsrc_owner_tp_dt_idx"),
                    models.Index(fields=["owner", "status", "created_at"], name="invsrc_owner_st_dt_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit_name", models.CharField(db_index=True, max_length=50)),
                ("multiplier", models.DecimalField(decimal_places=6, default=Decimal("1.000000"), max_digits=14)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_conversions",
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_units",
                "ordering": ["product_id", "unit_name", "-is_active", "-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "product"], name="prunit_owner_prod_idx"),
                    models.Index(fields=["owner", "unit_name"], name="prunit_owner_unit_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("supplier_name", models.CharField(blank=True, default="", max_length=200)),
                ("invoice_number", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("invoice_date", models.DateField(blank=True, db_index=True, null=True)),
                ("currency", models.CharField(blank=True, default="INR", max_length=10)),
                ("subtotal_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, db_index=True)),
                ("gst_rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("confidence", models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=6, db_index=True)),
                ("status", models.CharField(choices=[("captured", "Captured"), ("extracted", "Extracted"), ("matched", "Matched"), ("validated", "Validated"), ("ready", "Ready"), ("approved", "Approved"), ("rejected", "Rejected"), ("posted", "Posted"), ("failed", "Failed")], db_index=True, default="captured", max_length=20)),
                ("validation_warnings", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True, default="")),
                ("auto_approved", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_purchase_drafts",
                        to="commerce.order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_drafts",
                        to="procurement.invoicesource",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_drafts",
                        to="khataapp.party",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_drafts",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "status", "created_at"], name="pdraft_owner_st_dt_idx"),
                    models.Index(fields=["owner", "supplier", "created_at"], name="pdraft_owner_sup_dt_idx"),
                    models.Index(fields=["owner", "invoice_number"], name="pdraft_owner_invno_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_number", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("invoice_date", models.DateField(blank=True, db_index=True, null=True)),
                ("invoice_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, db_index=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("duplicate", "Duplicate"), ("posted", "Posted"), ("failed", "Failed")], db_index=True, default="draft", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_invoices",
                        to="procurement.purchasedraft",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_invoice_records",
                        to="commerce.order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_invoices",
                        to="procurement.invoicesource",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_invoices",
                        to="khataapp.party",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_invoices",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "supplier", "invoice_number"], name="purchinv_owner_sup_no_idx"),
                    models.Index(fields=["owner", "status", "created_at"], name="purchinv_owner_st_dt_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierAPIConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("token", models.CharField(blank=True, db_index=True, default="", max_length=64, unique=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled")], db_index=True, default="active", max_length=10)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_api_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_connections",
                        to="khataapp.party",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_api_connections",
                "ordering": ["supplier_id", "-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "supplier"], name="sapiconn_owner_sup_idx"),
                    models.Index(fields=["owner", "status"], name="sapiconn_owner_st_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierProductAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_name", models.CharField(db_index=True, max_length=200)),
                ("normalized_name", models.CharField(blank=True, db_index=True, default="", max_length=220)),
                ("confidence", models.DecimalField(decimal_places=3, default=Decimal("1.000"), max_digits=6)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_product_aliases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_aliases",
                        to="commerce.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_aliases",
                        to="khataapp.party",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_product_aliases",
                "ordering": ["supplier_id", "normalized_name", "-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "supplier"], name="spalias_owner_sup_idx"),
                    models.Index(fields=["owner", "normalized_name"], name="spalias_owner_nm_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField(default=1)),
                ("template", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_used_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_templates",
                        to="khataapp.party",
                    ),
                ),
            ],
            options={
                "db_table": "supplier_templates",
                "ordering": ["supplier_id", "-is_active", "-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "supplier", "is_active"], name="suptpl_owner_sup_idx"),
                    models.Index(fields=["owner", "is_active", "updated_at"], name="suptpl_owner_act_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseDraftItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_no", models.PositiveIntegerField(default=1)),
                ("raw_name", models.CharField(blank=True, default="", max_length=200)),
                ("quantity", models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=14)),
                ("unit", models.CharField(blank=True, default="", max_length=30)),
                ("rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("gst_rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("normalized_quantity", models.DecimalField(decimal_places=6, default=Decimal("0.000000"), max_digits=14)),
                ("normalized_unit", models.CharField(blank=True, default="", max_length=30)),
                ("match_confidence", models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=6, db_index=True)),
                ("match_method", models.CharField(blank=True, default="", max_length=30)),
                ("requires_review", models.BooleanField(db_index=True, default=False)),
                ("notes", models.CharField(blank=True, default="", max_length=240)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchasedraft",
                    ),
                ),
                (
                    "matched_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_draft_items",
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_draft_items",
                "ordering": ["draft_id", "line_no", "id"],
                "indexes": [
                    models.Index(fields=["draft", "requires_review"], name="pdi_draft_review_idx"),
                    models.Index(fields=["draft", "matched_product"], name="pdi_draft_prod_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raw_name", models.CharField(blank=True, default="", max_length=200)),
                ("qty", models.DecimalField(decimal_places=3, default=Decimal("0.000"), max_digits=14)),
                ("unit", models.CharField(blank=True, default="", max_length=30)),
                ("rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("gst_rate", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_items",
                        to="commerce.product",
                    ),
                ),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchaseinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_items",
                "ordering": ["purchase_invoice_id", "id"],
                "indexes": [
                    models.Index(fields=["purchase_invoice", "product"], name="purchit_inv_prod_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.UniqueConstraint(fields=("owner", "product", "unit_name"), name="uniq_owner_product_unit"),
        ),
        migrations.AddConstraint(
            model_name="supplierproductalias",
            constraint=models.UniqueConstraint(fields=("owner", "supplier", "normalized_name"), name="uniq_owner_supplier_alias"),
        ),
    ]

