# Generated by Codex on 2026-04-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_online",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("media_type", models.CharField(choices=[("image", "Image"), ("video", "Video")], db_index=True, default="image", max_length=10)),
                ("media", models.FileField(upload_to="product_media/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="products.product"),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [models.Index(fields=["product", "media_type", "sort_order"], name="products_pr_product_34d9b4_idx")],
            },
        ),
    ]

