# Generated by Codex on 2026-04-15

from django.db import migrations
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    db_alias = schema_editor.connection.alias
    qs = Product.objects.using(db_alias).filter(slug__isnull=True)
    for p in qs.iterator(chunk_size=500):
        if not p.sku:
            continue
        slug = slugify(f"{p.name}-{p.sku}")[:255]
        # Avoid collisions defensively.
        if Product.objects.using(db_alias).filter(slug=slug).exclude(id=p.id).exists():
            slug = slugify(f"{p.name}-{p.sku}-{p.id}")[:255]
        Product.objects.using(db_alias).filter(id=p.id).update(slug=slug)


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_online_fields_and_media"),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]

