# Generated by Django 5.2.5 on 2026-04-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_b2b_rules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productmedia',
            new_name='products_pr_product_51cb22_idx',
            old_name='products_pr_product_34d9b4_idx',
        ),
    ]
