# Generated by Django 5.2.5 on 2026-04-22 09:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_products_pr_product_34d9b4_idx_products_pr_product_51cb22_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_oos',
            field=models.BooleanField(db_index=True, default=False, help_text='Sell when out of stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='collections_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='is_physical',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
