# Generated by Codex on 2026-04-15

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storefront.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendors", "0001_initial"),
        ("products", "0003_backfill_product_slugs"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="customer_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(default="Home", max_length=60)),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("pincode", models.CharField(db_index=True, max_length=10)),
                ("district", models.CharField(blank=True, max_length=80)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("alternate_mobile", models.CharField(blank=True, max_length=15)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="storefront.customerprofile"),
                ),
            ],
            options={"indexes": [models.Index(fields=["profile", "is_default"], name="storefront__profile_c6c37d_idx")]},
        ),
        migrations.CreateModel(
            name="VendorProductListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_online", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("price_override", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vendor_listings", to="products.product"),
                ),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listings", to="vendors.vendor"),
                ),
            ],
            options={
                "unique_together": {("vendor", "product")},
                "indexes": [
                    models.Index(fields=["vendor", "is_online"], name="storefront__vendor__ab6c4c_idx"),
                    models.Index(fields=["vendor", "is_featured"], name="storefront__vendor__dfe0c9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishlists", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishlists", to="vendors.vendor")),
            ],
            options={"unique_together": {("vendor", "customer")}},
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishlisted_items", to="storefront.vendorproductlisting"),
                ),
                ("wishlist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="storefront.wishlist")),
            ],
            options={"unique_together": {("wishlist", "listing")}},
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("active", "Active"), ("converted", "Converted"), ("abandoned", "Abandoned")], db_index=True, default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="carts", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="carts", to="vendors.vendor")),
            ],
            options={"indexes": [models.Index(fields=["vendor", "customer", "status"], name="storefront__vendor__8d92f5_idx")]},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="storefront.cart")),
                (
                    "listing",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to="storefront.vendorproductlisting"),
                ),
            ],
            options={
                "unique_together": {("cart", "listing")},
                "indexes": [models.Index(fields=["cart", "listing"], name="storefront__cart_id_b0dd31_idx")],
            },
        ),
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(db_index=True, default=storefront.models._generate_order_number, max_length=40, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("packed", "Packed"), ("shipped", "Shipped"), ("delivered", "Delivered"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=20)),
                ("payment_status", models.CharField(choices=[("unpaid", "Unpaid"), ("initiated", "Initiated"), ("paid", "Paid"), ("failed", "Failed")], db_index=True, default="unpaid", max_length=20)),
                ("subtotal_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("shipping_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("invoice_pdf", models.FileField(blank=True, null=True, upload_to="store_invoices/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="storefront.customeraddress")),
                (
                    "billing_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal ERP order created on vendor acceptance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_store_orders",
                        to="orders.order",
                    ),
                ),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="store_orders", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="vendors.vendor")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["vendor", "status", "created_at"], name="storefront__vendor__4b0f73_idx"),
                    models.Index(fields=["vendor", "payment_status", "created_at"], name="storefront__vendor__4a7594_idx"),
                    models.Index(fields=["customer", "created_at"], name="storefront__customer_9d97f9_idx"),
                ]
            },
        ),
        migrations.CreateModel(
            name="StoreOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("listing", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="storefront.vendorproductlisting")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="storefront.storeorder")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.product")),
            ],
            options={"indexes": [models.Index(fields=["order", "product"], name="storefront__order_i_1e47c5_idx")]},
        ),
        migrations.CreateModel(
            name="StoreOrderStatusEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("packed", "Packed"), ("shipped", "Shipped"), ("delivered", "Delivered"), ("cancelled", "Cancelled")], db_index=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_events", to="storefront.storeorder")),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [models.Index(fields=["order", "created_at"], name="storefront__order_i_5b7956_idx")],
            },
        ),
        migrations.CreateModel(
            name="StorePaymentAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(db_index=True, max_length=30)),
                ("status", models.CharField(choices=[("initiated", "Initiated"), ("success", "Success"), ("failed", "Failed")], db_index=True, default="initiated", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("external_ref", models.CharField(blank=True, max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_attempts", to="storefront.storeorder")),
            ],
        ),
        migrations.CreateModel(
            name="StoreShipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(db_index=True, max_length=30)),
                ("tracking_number", models.CharField(blank=True, db_index=True, max_length=80)),
                ("status", models.CharField(choices=[("created", "Created"), ("pickup_requested", "Pickup requested"), ("in_transit", "In transit"), ("delivered", "Delivered"), ("failed", "Failed")], db_index=True, default="created", max_length=30)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="shipment", to="storefront.storeorder")),
            ],
        ),
    ]
