# Generated by Codex on 2026-04-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreWebhookDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(db_index=True, max_length=30)),
                ("dedupe_key", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(db_index=True, default="received", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="webhook_deliveries", to="vendors.vendor"),
                ),
            ],
            options={
                "unique_together": {("provider", "vendor", "dedupe_key")},
                "indexes": [models.Index(fields=["provider", "vendor", "created_at"], name="storefront__provider_1c8ce2_idx")],
            },
        ),
    ]

