# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0002_storewebhookdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeshipment",
            name="external_ref",
            field=models.CharField(blank=True, db_index=True, help_text="Provider shipment/order id.", max_length=120),
        ),
        migrations.AddField(
            model_name="storeshipment",
            name="courier_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="storeshipment",
            name="last_tracked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

