# Generated by Codex on 2026-04-15

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0003_storeshipment_shiprocket_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("commission_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wallet owner user for platform commission credits (e.g., Superadmin).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreSettlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("settled", "Settled"), ("failed", "Failed"), ("reversed", "Reversed")], db_index=True, default="pending", max_length=20)),
                ("commission_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("commission_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("vendor_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("vendor_wallet_txn_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("platform_wallet_txn_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="settlement", to="storefront.storeorder")),
            ],
            options={"indexes": [models.Index(fields=["status", "created_at"], name="storefront__status_0d6a78_idx")]},
        ),
    ]

