# Generated by Codex on 2026-04-15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0004_platformsettings_and_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="public_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

