# Generated by Codex on 2026-04-15

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0005_storeorder_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorproductlisting",
            name="rating_avg",
            field=models.DecimalField(db_index=True, decimal_places=2, default=Decimal("0.00"), max_digits=3),
        ),
        migrations.AddField(
            model_name="vendorproductlisting",
            name="rating_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]

