# Generated by Django 5.2.5 on 2026-04-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_whatsapp_account_links'),
        ('storefront', '0006_listing_rating_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cart',
            new_name='storefront__vendor__52b20f_idx',
            old_name='storefront__vendor__8d92f5_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='storefront__cart_id_10dfcc_idx',
            old_name='storefront__cart_id_b0dd31_idx',
        ),
        migrations.RenameIndex(
            model_name='customeraddress',
            new_name='storefront__profile_2f7be4_idx',
            old_name='storefront__profile_c6c37d_idx',
        ),
        migrations.RenameIndex(
            model_name='storeorder',
            new_name='storefront__vendor__348dc1_idx',
            old_name='storefront__vendor__4b0f73_idx',
        ),
        migrations.RenameIndex(
            model_name='storeorder',
            new_name='storefront__vendor__f91cc3_idx',
            old_name='storefront__vendor__4a7594_idx',
        ),
        migrations.RenameIndex(
            model_name='storeorder',
            new_name='storefront__custome_140180_idx',
            old_name='storefront__customer_9d97f9_idx',
        ),
        migrations.RenameIndex(
            model_name='storeorderitem',
            new_name='storefront__order_i_def1ce_idx',
            old_name='storefront__order_i_1e47c5_idx',
        ),
        migrations.RenameIndex(
            model_name='storeorderstatusevent',
            new_name='storefront__order_i_e8335b_idx',
            old_name='storefront__order_i_5b7956_idx',
        ),
        migrations.RenameIndex(
            model_name='storesettlement',
            new_name='storefront__status_1250fe_idx',
            old_name='storefront__status_0d6a78_idx',
        ),
        migrations.RenameIndex(
            model_name='storewebhookdelivery',
            new_name='storefront__provide_ec9f6e_idx',
            old_name='storefront__provider_1c8ce2_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorproductlisting',
            new_name='storefront__vendor__218f27_idx',
            old_name='storefront__vendor__ab6c4c_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorproductlisting',
            new_name='storefront__vendor__fbdce1_idx',
            old_name='storefront__vendor__dfe0c9_idx',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='commerce_order',
            field=models.OneToOneField(blank=True, help_text='Centralized billing order (commerce) for ledger/voucher flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_order', to='commerce.order'),
        ),
    ]
