# Generated by Django 5.2.5 on 2026-04-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0026_whatsapp_account_links"),
        ("storefront", "0007_add_commerce_order_link"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorCoupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_coupons",
                        to="commerce.coupon",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_coupons",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["vendor", "is_active"], name="storefront__vendor__coupon_idx")],
                "unique_together": {("vendor", "coupon")},
            },
        ),
        migrations.AddField(
            model_name="storeorder",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                help_text="Applied coupon code (from billing/commerce) at checkout time.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_orders",
                to="commerce.coupon",
            ),
        ),
        migrations.AddField(
            model_name="storeorder",
            name="referrer_code",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="storeorder",
            name="referral_reward_processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
