# Generated by Django 5.2.5 on 2026-04-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_vendorcoupon_and_storeorder_promotions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendorcoupon',
            new_name='storefront__vendor__d025d3_idx',
            old_name='storefront__vendor__coupon_idx',
        ),
    ]
